### ISSUE TITLE
Thanks! 🎉

### ISSUE THREAD

**Issue by torarnv** [jotta/jotta-cli-issues#1]
Just wanted to thank you for providing this! 😄

**Comment by Kimbsen** [comment]
Thank you for using it :)

We're very excited to see it in use after all this development time.

**Comment by fatso83** [comment]
Finally! I started using Hubic just to be able to backup my Linux machines, but they have _the worst service ever_ and I got [a bucket load of problems](https://twitter.com/kopseng/status/988084855354417153) when trying to _restore_ my files, so being able to go back to using Jottacloud would be a godsend, as they have never failed me in the basic things - except providing a Linux client during the first 7 years of use, that is :grinning: 

Great stuff!

One caveat: there should be some way for users to provide work back. I already saw some bash completions scripts in the issue list. That will easily be lost.
