### ISSUE TITLE
Get free programming help

### ISSUE THREAD

**Issue by rkarlsba** [jotta/jotta-cli-issues#10]
I guess this is a feature request, but hey.

If jotta were to open up the code of the client, I'm *positive* they will receive not only good bug reports, but also programming help and sufficient amounts of creds from the OSS society to allow the customer count to grow substantially. I can hardly see a reason for keeping something as simple as a backup client under closed source…

**Comment by jkaberg** [comment]
IMHO an better approach would be to add support to [Rclone](https://github.com/ncw/rclone), which has a very complete feature set. 

For example using [rclone serve](https://tip.rclone.org/commands/rclone_serve_restic/) along with [Restic](http://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) is a serious powerhouse, backup wise.
