### ISSUE TITLE
Can't synchronize files between Ubuntu desktop and Android phone

### ISSUE THREAD

**Issue by kjetil-kilhavn** [jotta/jotta-cli-issues#100]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jottad version    : 0.6.21799
jotta-cli version : 0.6.21799

**Description of problem:**
Can't synchronize files between Ubuntu desktop and Android phone because I can't find out how to add a synchronization folder to Ubuntu Desktop. None of the available commands in jotta-cli (output of jotta-cli --help) mentions synchronization folder.

**Expected:**
Can synchronize files between all systems as advertised: 
https://docs.jottacloud.com/en/articles/1292897-what-is-the-jottacloud-synchronization-folder
"The Jottacloud sync folder is a unique folder that is automatically synchronizes to all your computers and devices.

This means that files and folders you move or store in the Sync-folder, will automatically be uploaded to Jottacloud.
All actions done locally (renaming, deleting, moving etc.) will also be done/mirrored on Jottacloud.

Folders that you would like to synchronize, can be drag and dropped into the Jottacloud sync folder, that you find under "Favorites" in your computers file browser."

**jotta-cli status (`jotta-cli status`):**
Not relevant for this issue, but all paths show status "Up to date!"

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
Not relevant for this issue, but the log file (/var/lib/jottad/jottabackup.log) does not contain any error messages since yesterday (2018-12-28) 11:46:00 when there was an error getting account info (connection refused).

**Traceback**
Not relevant for this issue, and don't know how to get the output you want.

**Additional info:**
There are a couple of other issues for this, but they are both closed now.

**Comment by Kimbsen** [comment]
We will add sync support for jotta-cli. 

I don't have an eta but we are working on it.

**Comment by moritzheiber** [comment]
It'd be awesome to have this supported. Right now, working with the client on Linux for "regular user" activities (just a simply sync) is finicky at best.

**Comment by jonragnarsson** [comment]
When is the jotta-cli sync support coming? I found an old thread from 2018(!) where people were asking for this.

**Comment by bisand** [comment]
Any updates on when we can expect the sync feature for jotta-cli. This is the missing feature that prevents me from switching to Jottacloud for all my devices?
Do you need any help from the community? Maybe go open source? There are several people out there both capable and willing to contribute. :)
Hope to see the feature soon!

**Comment by jchalifour** [comment]
Great that sync is in the works! I'd like to add that I find it especially useful for a sync feature to allow the user to specify which folders will synchronize with which folders. That's to say, it'd be really nice to be able to tell Jottacloud to sync folder A (computer 1) with folder B (computer 2) rather than have a single sync folder that both computers function with.

**Comment by aerique** [comment]
More info on sync support for jotta-cli would be welcome!

**Comment by coopersimon** [comment]
Hi all, you can now test sync on the unstable channel. It is currently in beta and we'll release it to stable once we're sure it's ready.

If you would like to give it a try, have a look at the README to find out how to get unstable. Then run `jotta-cli sync` to see how to get started.

**Comment by aerique** [comment]
Awesome, running it now!

**Comment by superDuperCyberTechno** [comment]
Where's the docs on this? I'm running version 0.11.44593 and I can't see anything on this...
