### ISSUE TITLE
Log file should be in /var/log

### ISSUE THREAD

**Issue by rkarlsba** [jotta/jotta-cli-issues#102]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
-------------------------------------------
jottad executable :
jottad appdata    : /var/lib/jottad
jottad version    : 0.6.21799
jotta-cli version : 0.6.21799
-------------------------------------------
OK
**Description of problem:**
log file is under /var/lib
**Expected:**
it should be under /var/log

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by coopersimon** [comment]
This has been added to the newest version of jottad (0.10.43844). You can set a custom location via the .ini file.

You can add
```
[settings]
LogfileDir=/var/log
```

To a file called `/etc/jottad/config.ini`

More details here: https://docs.jottacloud.com/en/articles/2750154-jottacloud-cli-configuration
