### ISSUE TITLE
Where are my photos?

### ISSUE THREAD

**Issue by Antwelm** [jotta/jotta-cli-issues#107]
jotta-cli ls -l
Name     Size  Checksum  LastModified  
-------  ----  --------  ------------  
Archive                                
Backup                                 
Sync                             

So, where do I find my photos?

**Comment by Kimbsen** [comment]
We just released version 0.6.24236 which adds Photos as an experimental download root.

**Comment by Antwelm** [comment]
Haven't been able to test, but that's awesome.
