### ISSUE TITLE
Missing newline in "ls" command

### ISSUE THREAD

**Issue by teichmauer** [jotta/jotta-cli-issues#114]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
-------------------------------------------
jottad executable : 
jottad appdata    : /var/lib/jottad
jottad version    : 0.6.24251
jotta-cli version : 0.6.24251
-------------------------------------------

**Description of problem:**

After the output of the "jotta-cli ls" command, no newline is appended:
$ jotta-cli ls
Backup Photos Sync Archive $

Output of strace:
write(1, "Archive ", 8)                 = 8
write(1, "Backup ", 7)                  = 7
write(1, "Photos ", 7)                  = 7
write(1, "Sync ", 5)                    = 5
write(1, "\33[?25h", 6)                 = 6

**Expected:**
$ jotta-cli ls
Backup Photos Sync Archive
$

**jotta-cli status (`jotta-cli status`):**
```
------------------------------------------------------------------------------
 Account   : jottacloud@nospam.chugle.ch on Jottacloud
 Usage     : 178.82GiB / ( Unlimited )
 Device    : peLenny
 Backups   :
------------------------------------------------------------------------------
   Path      : /home/patrik/Jottacloud
   Files     : 81 files / 141.26MiB
   Status    : Up to date!

------------------------------------------------------------------------------

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
none
```

**Traceback**
```
none
```

**Additional info:**

none

**Comment by Kimbsen** [comment]
We've just released version 0.7.35160 which should fix this issue.
