### ISSUE TITLE
Downloading a folder 'a' into folder 'b' doubles folder 'a'

### ISSUE THREAD

**Issue by teichmauer** [jotta/jotta-cli-issues#115]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.6.24251

**Description of problem:**
I have a file under a folder hierarchy Sync/a/DSC_0460.JPG
jotta-cli download Sync/a . (to the current directory) results correctly in folder "a".
jotta-cli download Sync/a b (to an existing folder b) results in b/a/a

$ jotta-cli download Sync/a .
> starting download Sync/a => /home/patrik/junk/dl
[..]
$ ls a
DSC_0460.JPG
$ mkdir b;chmod 777 b
$ jotta-cli download Sync/a   b
The download [..] Continue?: yes
[..]
$ ls -R b
b:
a
b/a:
a
b/a/a:
DSC_0460.JPG

**Expected:**
b/a/DSC_0460.JPG

**jotta-cli status (`jotta-cli status`):**
```
------------------------------------------------------------------------------
 Account   : jottacloud@nospam.chugle.ch on Jottacloud
 Usage     : 178.82GiB / ( Unlimited )
 Device    : peLenny
 Backups   :
------------------------------------------------------------------------------
   Path      : /home/patrik/Jottacloud
   Files     : 81 files / 141.26MiB
   Status    : Up to date!

------------------------------------------------------------------------------

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
none
```

**Traceback**
```
none
```

**Additional info:**
none

**Comment by Kimbsen** [comment]
We've just released version 0.7.35160 which should fix this issue.
