### ISSUE TITLE
jotta-cli cannot connect to jottad

### ISSUE THREAD

**Issue by lvbaal** [jotta/jotta-cli-issues#118]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.6.24251-1
**Description of problem:**
jottad has started from runit, but jotta-cli status gives: "Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?"
**Expected:**
Normal response from jotta-cli status

**jotta-cli status (`jotta-cli status`):**
```
see above
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
pid:1265 2020/09/27 15:22:50 Starting /usr/bin/jottad version 0.6.24251 as 994(jottad)/979
pid:1265 2020/09/27 15:22:50 jottad.init
pid:1265 2020/09/27 15:22:50 jottad.init.appdata => /var/lib/jottad
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/.ignore (1598102928|490)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/db (1601212896|32768)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/downloads
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/downloads/history (1601212896|16384)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/jottabackup.log (1601212970|2903)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/nstore - (f27af34fccaea0094c8ff67242abdd05|1601212896|16384)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/store - (68404a216d026ab4b8bcad8ecdee8450|1601212896|254)
pid:1265 2020/09/27 15:22:50 jottad.appdata     /var/lib/jottad/userconfig.json (1601212896|185)
pid:1265 2020/09/27 15:22:50 Error loading existing session on auth.New loadsession: not found
pid:1265 2020/09/27 15:22:50 jottad.init.cfg.downloadratae => 0B
pid:1265 2020/09/27 15:22:50 jottad.init.cfg.uploadrate => 0B
pid:1265 2020/09/27 15:22:50 jottad.init.cfg.scaninterval =>  1h0m0s
pid:1265 2020/09/27 15:22:50 Unable to get device id : No mac addr detected
pid:1265 2020/09/27 15:22:50 Error getting device id No mac addr detected
pid:1265 2020/09/27 15:22:50 No mac addr detected
pid:1519 2020/09/27 15:22:51 Starting /usr/bin/jottad version 0.6.24251 as 994(jottad)/979
pid:1519 2020/09/27 15:22:51 jottad.init
pid:1519 2020/09/27 15:22:51 jottad.init.appdata => /var/lib/jottad
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/.ignore (1598102928|490)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/db (1601212896|32768)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/downloads
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/downloads/history (1601212896|16384)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/jottabackup.log (1601212971|4414)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/nstore - (f27af34fccaea0094c8ff67242abdd05|1601212896|16384)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/store - (68404a216d026ab4b8bcad8ecdee8450|1601212896|254)
pid:1519 2020/09/27 15:22:51 jottad.appdata     /var/lib/jottad/userconfig.json (1601212970|185)
pid:1519 2020/09/27 15:22:51 Error loading existing session on auth.New loadsession: not found
pid:1519 2020/09/27 15:22:51 jottad.init.cfg.downloadratae => 0B
pid:1519 2020/09/27 15:22:51 jottad.init.cfg.uploadrate => 0B
pid:1519 2020/09/27 15:22:51 jottad.init.cfg.scaninterval =>  1h0m0s
pid:1519 2020/09/27 15:22:51 jottad.init.user => no user logged in
pid:1519 2020/09/27 15:22:51 jottad.init.done => ok
pid:1519 2020/09/27 15:22:51 jottad.startup
pid:1519 2020/09/27 15:22:51 jottad.startup.auth.patch
pid:1519 2020/09/27 15:22:51 api.grpc.active => 127.0.0.1:14443
pid:1519 2020/09/27 15:22:54 jottad.startup => ok
pid:1519 2020/09/27 15:22:54 Error checking for new versions Get https://repo.jotta.us/archives/VERSION: dial tcp: lookup repo.jotta.us: Temporary failure in name resolution
```

**Traceback**
```

```

**Additional info:**
Steps taken to try and resolve the issue:
- stop jottad ('sv down jottad')
- removed everything in /var/lib/jottad
- start jottad (' sv up jottad' )
- jotta-cli login
wi\ich gives same connection error

**Comment by follesoe** [comment]
Have the same issue. Appear to have started on Friday or Saturday? I created a Docker container to run back-ups from my Synology NAS which worked just fine - but it now fails with the above error. I first assumed it was related to the Docker Image I was using, so I tried to recreate everything from scratch locally - but I get the same error in my newly created image. Looking at the log file I also see that `api.grpc.active => 127.0.0.1:14443` log message, indicating that it should be up an running?

**Comment by Swallowtail23** [comment]
Yep, same issue. Seems to actually start according to journalctl, but no can longer be interrogated with jotta-cli status:

`Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?`

Multiple machines all running jotta-cli, same issue.

I would suggest this is a critical issue which needs rather urgent attention.

**Comment by pucko73** [comment]
I have the same issue on multiple machines.  Log:

pid:15449 2020/09/28 09:28:43 Starting /usr/bin/jottad version 0.6.24251 as 0(root)/0
pid:15449 2020/09/28 09:28:43 jottad.init
pid:15449 2020/09/28 09:28:43 jottad.init.appdata => /var/lib/jottad
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/.ignore (1571137078|490)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/bck
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/db (1601277844|191754240)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/downloads
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/downloads/history (1571125108|16384)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/jottabackup.log (1601278123|665)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/nstore - (2c09cf50c6f354f97edcc1cb12de0fa9|1601274717|65536)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/store - (036369293dcd7d2170cdc7790e9b2b38|1601277668|254)
pid:15449 2020/09/28 09:28:43 jottad.appdata    /var/lib/jottad/userconfig.json (1601277668|185)
pid:15449 2020/09/28 09:28:43 jottad.init.cfg.downloadratae => 0B
pid:15449 2020/09/28 09:28:43 jottad.init.cfg.uploadrate => 0B
pid:15449 2020/09/28 09:28:43 jottad.init.cfg.scaninterval =>  1h0m0s
pid:15449 2020/09/28 09:28:43 jottad.init.user => [5da5649481d9f20133753bb7] on [XXX] @ [2fd7f0dcfe8b820830aea8ef3b882148]
pid:15449 2020/09/28 09:28:43 jottad.init.loadedbackup /volume1/Downloads => Downloads
pid:15449 2020/09/28 09:28:43 jottad.init.loadedbackup /volume1/mssql => mssql
pid:15449 2020/09/28 09:28:43 jottad.init.loadedbackup /volume1/photo => photo
pid:15449 2020/09/28 09:28:43 jottad.init.done => ok
pid:15449 2020/09/28 09:28:43 jottad.startup
pid:15449 2020/09/28 09:28:43 jottad.startup.confirm-remote
pid:15449 2020/09/28 09:28:43 api.grpc.active => 127.0.0.1:14443
pid:15449 2020/09/28 09:28:43 running 3 delayed startup tasks
pid:15449 2020/09/28 09:28:43 updating account info true true
pid:15449 2020/09/28 09:28:43 jottad.startup.confirm-remote => ok
pid:15449 2020/09/28 09:28:43 jottad.startup => ok

**Comment by mabahj** [comment]
Same issue. I've verified with ` sudo lsof -i -P -n | grep jottad` that it indeed is listening on 127.0.0.1:14443.

**Comment by Kimbsen** [comment]
We have found the error and are in the process of creating a new release. Sorry for the inconvenience

**Comment by pucko73** [comment]
> We have found the error and are in the process of creating a new release. Sorry for the inconvenience

Great news!

**Comment by Kimbsen** [comment]
We released version 0.6.32724 which fixes the problem.

It was caused by the expiry of the tls certificate jottad and jotta-cli use to communicate with eachother.

The expiry date had been logged incorrectly in our internal issue tracker so we didn't expect it to expire yet and thus we didn't preemptively renew it.

**Comment by lvbaal** [comment]
> We released version 0.6.32724 which fixes the problem.
> 
> It was caused by the expiry of the tls certificate jottad and jotta-cli use to communicate with eachother.
> 
> The expiry date had been logged incorrectly in our internal issue tracker so we didn't expect it to expire yet and thus we didn't preemptively renew it.

That's great! When could I expect the AUR to be updated with this release? The latest release on AUR at the moment is 0.6.24251.1 from March 21st 2020.

**Comment by Kimbsen** [comment]
I'm not sure about the arch packages. We don't maintain them.

**Comment by lvbaal** [comment]
> I'm not sure about the arch packages. We don't maintain them.

Could you outline for me then how I would get this update on an arch system? Thanks!

**Comment by existemi** [comment]
> > I'm not sure about the arch packages. We don't maintain them.
> 
> Could you outline for me then how I would get this update on an arch system? Thanks!

The maintainer of the AUR package must be contacted: https://aur.archlinux.org/packages/jotta-cli/

**Comment by lvbaal** [comment]
> > > I'm not sure about the arch packages. We don't maintain them.
> > 
> > 
> > Could you outline for me then how I would get this update on an arch system? Thanks!
> 
> The maintainer of the AUR package must be contacted: https://aur.archlinux.org/packages/jotta-cli/

The maintainers of the AUR package (Morten Linderud, foxboron@archlinux.org and Joakim Nylen, aur@joakim.nylen.nu) informed me that they're not maintaining the AUR package any longer.
Would it be possible for jottacloud to take upon themself to maintain the arch package?
I don't know how to do this myself.

**Comment by Kimbsen** [comment]
I'm sorry for now we do not have anyone that could do that. 

You can always download the release manually from here and setup it up yourself: https://repo.jotta.us/archives/linux/

**Comment by dimme** [comment]
Just experienced this problem on a brand new Ubuntu Focal installation.
