### ISSUE TITLE
Add info about unsyncable files in "jotta-cli Status"

### ISSUE THREAD

**Issue by eljejer** [jotta/jotta-cli-issues#123]
**jotta-cli release (`jotta-cli version`):**
jottad executable : /usr/bin/jottad
jottad appdata    : /var/lib/jottad
jottad version    : 0.7.35160
jotta-cli version : 0.7.35160

**Description of problem:**
When a file does not meet the criteria for backing up, it will be skipped during backup.
jotta-cli reports this as follows:
'Status    : 1 files (113.16KiB) have not been backed up'

**Expected:**
It would be nice if jotta-cli would report which file(s) it is concerning

**jotta-cli status (`jotta-cli status`):**

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**

**Traceback**

**Additional info:**
On a regular basis files come into my Documents folder without the right permission/ownership.
For jottad to be able to process them they have to have GID jottad and execute permission for jottad.
With this in mind it would be nice if jotta-cli reports accurately in stead of generally

**Comment by Kimbsen** [comment]
I agree that is missing. We'll prioritize getting it in the next release.

**Comment by coopersimon** [comment]
Hi,

We have added a new feature `status -v` to the unstable release channel. This will inform you of specific file errors. It will be included in the next stable release, but feel free to check out unstable - any feedback is appreciated!

**Comment by lvbaal** [comment]
Thanks for this- However, I suppose the specific error because of which I requested this feature will not occur any more so often because I made a change in the jotta configuration after I requested this; I changed User=jottad into User=<my user> in the jottad.service file. Now jottad can read all the files in the backup folders anyway.

**Comment by Kimbsen** [comment]
We released 0.8.36055 today which should resolve this.
