### ISSUE TITLE
Can't add my photo directory

### ISSUE THREAD

**Issue by GFRT-tech** [jotta/jotta-cli-issues#127]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jotta-cli version
-------------------------------------------
jottad executable : /usr/bin/jottad
jottad appdata    : /var/lib/jottad
jottad version    : 0.8.36055
jotta-cli version : 0.8.36055
-------------------------------------------

**Description of problem:**
Interpreting [./Images] as [/home/user/Images]
ERROR  Cannot add /home/user/Images to backup: jottad does not have permission to stat the folder

**Expected:**
I want to add my / home / user / Images directory
I want to add my /media/user/drive/Takeout/Google Photos (USB Backup Drive)

**jotta-cli status (`jotta-cli status`):**
```
------------------------------------------------------------------------------
 Account   : **************** on Jottacloud
 Usage     : 7.51GiB / 1.00TiB 
 Device    : *********************************
------------------------------------------------------------------------------
 No folders added to backup yet
------------------------------------------------------------------------------
OK


```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
The jottad process needs to have have the appropriate permissions to backup files. 

There is more information [here](https://docs.jottacloud.com/en/articles/2932989-jottacloud-cli-and-permissions-on-linux)
