### ISSUE TITLE
jotta-cli ls -l should have a switch for omitting the header

### ISSUE THREAD

**Issue by magnush0lm** [jotta/jotta-cli-issues#137]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**

**Description of problem:**

# jotta-cli.exe ls -lh /archive
Name             Size  Checksum  LastModified
---------------  ----  --------  ------------
blah
blah2

**Expected:**

# jotta-cli.exe ls -lh /archive
blah
blah2

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by coopersimon** [comment]
Hi magnush0lm, thanks for the requests. We'll evaluate them internally.

**Comment by coopersimon** [comment]
This is in the newest version (0.11.44593). Try `jotta-cli ls -lH`.

Thanks for the suggestion!
