### ISSUE TITLE
jotta-cli ls should be able to output as json

### ISSUE THREAD

**Issue by magnush0lm** [jotta/jotta-cli-issues#138]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**

**Description of problem:**

**Expected:**

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by coopersimon** [comment]
This is in the newest release (0.11.44593). Try `jotta-cli ls --json`

Thanks for the suggestion!
