### ISSUE TITLE
Can't add Folders to archive

### ISSUE THREAD

**Issue by Exellent1988** [jotta/jotta-cli-issues#14]
First of all : NICLY DONE!

Now I have a little feature request:

The possebillity to move hole Folderstructures to the Archive.

Wen i try to do this i get the following error:

jotta-cli archive /backup/zips/
Interpretting [/backup/zips/] as [/backup/zips]
Error: [2] read /backup/zips: is a directory

**Comment by Kimbsen** [comment]
We don't have any plans to add archiving of a folder structure.

See #2 for an example of adding multiple files using jotta-cli archive.

If you just want to backup a folder structure once, you can use
``` jotta-cli add /path/to/folder ```
and once backup is complete
```jotta-cli rem /path/to/folder ```
and the files are still backed up.

**Comment by Exellent1988** [comment]
I know that I can do it that way, but If i want to have a folder moved to the archive i have to do it manually in the Web-frontend eventually. Not quite handy. To bad, i guess for that i will then still use jottalib :)

**Comment by lolicato** [comment]
Hi, 

I had the same problem yesterday but I worked around by writing this simple bash script.
It is not the most elegant way but  it is doing the job :)
It just reads the tree of the directory and uses their absolute paths to archive every
single file inside each directory.

The only problem is that it re-creates the same path you digit as "input folder"
inside Jottacloud:

If you digit:
./jotta-cli-archive.sh ../input_folder  my_backup

You will find in your Archive folder inside Jottacloud this directory tree:

my_backup/../input_folder

So, just use the final path :)
./jotta-cli-archive.sh  input_folder  my_backup


I have just upload it and I am testing it now.

https://github.com/lolicato/jotta-cli-archive.git

 :)
