### ISSUE TITLE
Support for OpenSUSE or direct download to RPM

### ISSUE THREAD

**Issue by R0flcopt3r** [jotta/jotta-cli-issues#142]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**

N/A

**Description of problem:**

Unable to install on OpenSUSE (Tumbleweed)

**Expected:**

Have access to the raw RPM installation without adding repository, or repository for OpenSUSE.

**jotta-cli status (`jotta-cli status`):**

N/A

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**

N/A

**Traceback**

N/A

**Additional info:**

**Comment by roflmao** [comment]
Hi,

We provide tarballs on: https://repo.jotta.us/archives/

We do not plan to support OpenSUSE at the moment, im sorry.
