### ISSUE TITLE
Request: WebHook compatibility with Discord

### ISSUE THREAD

**Issue by Eryniox** [jotta/jotta-cli-issues#144]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):** jotta-cli_0.10.42740_windows_amd64.msi

**Description of problem:** I've added a webhook, that points towards Discord. And by adding "/slack" to the end of the URL, it should work fine. And it worked perfect for many months, with version: jotta-cli_0.6.24251_windows_amd64

But with the current version, I get the error: 
* 
2021/05/04 13:49:49 Invalid status code for webhook[400] {"description": ["This field is required"]}

And I can't figure out why. I tried adding a webhook towards: https://webhook.site/ , and then testing with the json i got, directly to the Discord webhook, with Powershell. And this worked fine... So it's maybe some formatting?

**Expected:**
Status messages in Discord channel.

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
Thanks for the report. This sounds like something we should support. We'll try to get it sorted for the next release.

**Comment by Eryniox** [comment]
I forgot to mention; when starting and stopping jottad, the messages come through to Discord just fine. It's only the status-update every x hours/minutes that give this error.

(also tested version: jotta-cli_0.10.43844_windows_amd64.msi; same result)

**Comment by coopersimon** [comment]
Did you see the full list of backups in the discord messages before?

**Comment by Eryniox** [comment]
![Skjermbilde 2021-05-19 203247](https://user-images.githubusercontent.com/16980552/118865769-9a407500-b8e1-11eb-914a-3e1ba13e54df.png)

Yes, like the ".\jotta-cli.exe status". 
And Start-stopping the service pops up in Discord. And weirdly enough one status message popped up yesterday, the first since April 20.

**Comment by coopersimon** [comment]
The newest version shouldn't fix it, we haven't touched it there. However we have found the problem now, a fix should be in the next version!

**Comment by coopersimon** [comment]
If you want to try it out, the fix for this is in unstable version 0.10.44290. It will be in the next stable version.

**Comment by coopersimon** [comment]
This is fixed in the newest stable (0.11.44593).

**Comment by Eryniox** [comment]
Thanks alot for this. I was planning to test the beta last weekend, but never got around to it. I installed the newest version on Thursday evening, and it worked perfectly! 
It's awesome to be able to check the status in Discord again! 😁
