### ISSUE TITLE
Does not support encrypted home folder

### ISSUE THREAD

**Issue by carestad** [jotta/jotta-cli-issues#16]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**

0.3.4269

**Description of problem:**

`jotta-cli add /home/alexander/Jotta`

```
21:14 [alexander@foobar /home/alexander/]$ jotta-cli add Jotta
Interpretting [Jotta] as [/home/alexander/Jotta]
Error: [2] Could not add path to backup: Unsupported filesystem [ECRYPTFS_SUPER_MAGIC] for key [0xf15f]
```

**Expected:**

Expected to work.

**jotta-cli status (`jotta-cli status`):**
```
---------------------------------------------------------
 Account   : ****************
 Usage     : 0bytes / 5.00GiB
 Backups   :
---------------------------------------------------------
   Path      : /opt/alexander/jotta
   Files     : 1 files / 12bytes
   Status    : Up to date!
---------------------------------------------------------
OK

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**

Don't seem to have this folder and file.

**Comment by rkarlsba** [comment]
Same as #9 - they have a whitelist for supported filesystems for reasons not explained. Everything is posix anyhow, so it really shouldn't matter.

**Comment by Kimbsen** [comment]
This should be resolved now with the 0.4 release.

**Comment by rkarlsba** [comment]
You said nfs etc wasn't supported earlier because if jottad started and the filesystem wasn't mounted, the data would be moved to trash. I guess this is the same with other filesystems? If so, a scenario of the data filesystem not getting mounted for some reason (for instance a bad cable) would probably do the same thing? I mean - if my data drive goes down, I'd have to remove it from fstab and boot up the system without it to debug further.

What would your suggestion be if something like this happens? I've seen it before, and I'll probably see it again. Keeping the data for some time (a month or two?) before scrapping them would probably be a good idea.

**Comment by Kimbsen** [comment]
When deleting data on the server it is moved to the trash can where it stays for 30 days before being permantely deleted. 

As for a suggestion, you could always pause jottad for the duration you expect your repairs to take. Or just stop it while you debug, and start it again after. 

That said, we did add as an error condition that if the root of an added folder appears empty jottad will not do nothing and status+hooks will display an error message.

So for instance if you mounted some filesystem to /mnt/data and then added /mnt/data to backup, if at a later time it for some reason doesn't mount properly and /mnt/data then appears empty then jottad will just warn you that it appears unmounted and not delete the contents. 

Though if you had a file in the folder /mnt/data ( before mounting the filesystem to /mnt/data ) this will break the error condition and then once the filesystem becomes unmounted this one file will be uploaded and everything else moved to the trash can.

**Comment by rkarlsba** [comment]
So - if you

# mkdir /mnt/data
# touch /mnt/data/asdf
# mount /mnt/data
(backup)
# umount /mnt/data
…then jottad decides everything is deleted?

If so - why don't you check the filsystem ID (stat -c %i /fs)?

**Comment by rkarlsba** [comment]
Warning: The path you attempt to add is located on a mounted file system.

(I wonder how I should be able to backup a non-mounted filesystem…)

**Comment by torarnv** [comment]
> If so - why don't you check the filsystem ID (stat -c %i /fs)?

This seems like it could be a fix yes.

But a good workaround for now is to not keep anything in your mounted dir, and to only add the roots of any mounted fs
