### ISSUE TITLE
CPU Usage jottad

### ISSUE THREAD

**Issue by frithrah** [jotta/jotta-cli-issues#167]
**jotta-cli release (`jotta-cli version`):**
jottad version    : 0.12.51202
jotta-cli version : 0.12.51202

**Description of problem:**
jottad is always at the top of my CPU usage chart. It's not using much CPU but I'm surprised it's using any when files aren't changing. Are you using inotify?

**Expected:**
No CPU usage when idle.

**jotta-cli status (`jotta-cli status`):**
```
------------------------------------------------------------------------------
   Status    : Up to date
------------------------------------------------------------------------------
OK
```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```

```

**Traceback**
```

```

**Additional info:**
Thank you for all your good work!

**Comment by roflmao** [comment]
Sharing some more details regarding cpu usage would be helpful.
Also logs for showing what the client is doing.

We use inotify if scaninterval is set to 0.

**Comment by frithrah** [comment]
Thanks for the `scaninterval` info. I set it to zero but I still have a constant 0.7% CPU on jottad. I wonder what it's doing all the time?

Here's my config:
```
> jotta-cli config get
maxuploads               : 2
logscanignores           : false
webhookstatusinterval    : 6h0m0s
slowmomode               : 0
logtransfers             : false
photosmonthastext        : true
downloadrate             : unlimited
uploadrate               : unlimited
maxdownloads             : 2
scaninterval             : 0
checksumreadrate         : 52.43MB/s
OK
```

The `jottabackup.log` doesn't show any activity unless a file is changed in a watched directory.

Is there anything else I can share that will help?

**Comment by roflmao** [comment]
We always strive to improve idle resource usage, but also there is some housekeeping that jottad needs to perform.

**Comment by frithrah** [comment]
Could it perhaps save housekeeping for when it has to sync. I'm sure you can do without your busy loop - the laptop batteries of the world will thank you.

**Comment by ihatetoregister** [comment]
Experience the same on 0.15.110283 still
