### ISSUE TITLE
Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?

### ISSUE THREAD

**Issue by unik-web** [jotta/jotta-cli-issues#172]
I get this error when i run jotta-cli login

Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?

I have disabled firewall and didn't helped.
I have also tried added new port.

Do anybody have some suggestions ?

**Comment by Kimbsen** [comment]
How did you install it? And what OS is it running on? 

If its running on linux you need to call `run_jottad` to start jottad as we changed how jotta-cli and jottad communicates in version 0.12. More info here: https://docs.jottacloud.com/en/articles/1436855-jottacloud-cli-for-linux-debian-packages

**Comment by unik-web** [comment]
Hi again,
Thanks for returning back. 
I have followed excaly as documentation said. 
I'm using ubuntu 18.04 LTS server and when I run `run_jottad` I get this error messasge 
`ubuntu@jottacloud-test:~/www$ run_jottad
Starting via systemd...
Failed to connect to bus: No such file or directory
Failed to load systemd units. If systemd is not supported, please 'export JOTTAD_SYSTEMD=0' before running this command.
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
run_jottad: Success!
`

**Comment by Kimbsen** [comment]
There looks to be something wrong with systemd. 

Does the command ```systemctl --user status ``` produce any errors?

If you are not using systemd you need to ```export JOTTAD_SYSTEMD=0``` before running ```run_jottad```

**Comment by unik-web** [comment]
Found out what is it. Because I was running under LXD default ubuntu user and it's crashing there. When I tried with custom login it was working perfectly. That's why issue was becoming. 

Thanks for help :-)
