### ISSUE TITLE
Telia Sky and jotta-cli token generation

### ISSUE THREAD

**Issue by BjornRuud** [jotta/jotta-cli-issues#173]
I can't log in anymore to Telia Sky using jotta-cli since token generation is gone. The page https://sky.telia.no/web/secure does not have token generation, and the other settings pages do not either. According to issue #89 this has happened before and is a regression.

**Comment by BjornRuud** [comment]
When you say "we and Telia" are you referring to only your Telia branded version or will CLI support disappear from Jottacloud also in the future? The CLI version is the reason I want to use Jottacloud.

**Comment by Kimbsen** [comment]
I was referring to the Telia branded version. CLI for jottacloud will not dissappear.

**Comment by Kimbsen** [comment]
I've heard back now and we will be adding token generation back for Telia Sky. Possibly limited to users who already have a CLI registered ( until we can get proper support through Telias auth system ).  I can't say exactly when it will be back, but it is happening.

**Comment by BjornRuud** [comment]
That's great news. The various whitelabel solutions should have feature parity. For my part I ended up subscribing to Jottacloud since I decided that I didn't want access to my data be dependent on my ISP.

**Comment by Kimbsen** [comment]
CLI Token generation is back for Telia Sky!
