### ISSUE TITLE
Feature request: Ability to schedule jottad to only run within specified time interval

### ISSUE THREAD

**Issue by Soerboe** [jotta/jotta-cli-issues#18]
It would be very convenient to be able to schedule jottad to run within specified time intervals. I know that it is possible to set scan interval. However I would like to set a start time and end time for when the backup should run. A typical use case would be to only backup during night hours.

**Comment by NoLooseEnds** [comment]
Cron?

**Comment by Soerboe** [comment]
@NoLooseEnds cron could be used as a workaround. But it is a hassle to have to make two cron jobs (start/stop the service) and to make sure it also works whenever the machine is restarted at various times of the day.

I believe it would be better if the jottad service itself had scheduling capabilities. The service itself can stop more gracefully then a service stop.

**Comment by Foxboron** [comment]
Systemd timers solve this nicely, a lot better then cron.

**Comment by torarnv** [comment]
Agreed, this doesn't sound in scope for jotta-cli, or at least not of high priority. 

Why do you need to start/stop jottad though? Isn't it enough to keep it running, with a high scan interval, and then issue a manual scan from cron? (possibly re-setting the scan interval so that it basically never times out?)

**Comment by Soerboe** [comment]
@Foxboron 
How do you schedule a service to only run within a specified time interval using systemd? E.g. from noon to 6am. I can not find any examples of this. 

@torarnv 
Let be explain using an example; Once in a while I import 50 GB of video files from my camera. These files should now be synced to Jottacloud. However, I am only on an ADSL line so the upload speed is not great. Therefore I would like the backup to only run at night (e.g. from noon to 6am) so any Internet browsing during the day is not affected by the backup (jottad consumes most of the bandwidth).

This is the reason I currently stop jottad at 6am. The solution you're proposing does not stop/pause the backup whenever the end of the scheduling interval is reached.

**Comment by Foxboron** [comment]
From the `systemd.time` man page.
"Two values separated by ".."  may be used to indicate a range of values; ranges may also be followed with "/" and a repetition value."

So i guess something along the lines of `OnCalendar=12..06:00:00` without further testing.

**Comment by Soerboe** [comment]
I doesn't seem to work here. This is the error when trying to start the timer using
`systemctl start writer.timer`

    [/etc/systemd/system/writer.timer:5] Failed to parse calendar specification, ignoring: 06..12:00:00
    writer.timer: Timer unit lacks value setting. Refusing.

**Comment by EldarAron** [comment]
Cant you just run a cron with the pause command?
`jotta-cli pause 6h` @ midnight?

**Comment by Soerboe** [comment]
@EldarAron Sure, but this issue was written before version 0.4 was released. I just haven't remembered to close it.

However the question about systemd timers is still unanswered (for anyone reading this thread later on).

**Comment by Soerboe** [comment]
Version 0.4 of jotta-cli introduced a `pause` command (`jotta-cli pause`) which resolves this issue.
