### ISSUE TITLE
jotta-cli windows: Please update from 0.15.0 to version 0.15.78571

### ISSUE THREAD

**Issue by magnush0lm** [jotta/jotta-cli-issues#188]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jotta-cli version
-------------------------------------------
 A new version of Jotta Cli is available.
 Please update from 0.15.0 to version 0.15.78571

 To update jotta-cli just download and install
 most recent build from

 https://repo.jotta.us/archives/windows/amd64/
-------------------------------------------
-------------------------------------------
jottad executable : C:\Users\magnus\Desktop\jottad.exe
jottad appdata    : C:\Users\magnus\.jottad
jottad logfile    : C:\Users\magnus\.jottad\jottabackup.log
jottad version    : 0.15.0
remote version    : 0.15.78571
jotta-cli version : 0.15.0
-------------------------------------------
OK

**Description of problem:**
The latest release at https://repo.jotta.us/archives/windows/amd64/ is 0.15.0,

**Expected:**
Either there should be no update warning, or version 0.15.78571 should be made available

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by magnush0lm** [comment]
![image](https://user-images.githubusercontent.com/15702649/231944243-53b71516-7fe5-4530-9077-5f200c510c13.png)

**Comment by magnush0lm** [comment]
0.15.78571 is, however, available for Linux

![image](https://user-images.githubusercontent.com/15702649/231944361-8c22ccb3-20cb-4a12-a948-b6d2f82f7b01.png)

**Comment by Kimbsen** [comment]
Thanks for the report. 

The version listed on repo.jotta.us as 0.15.0 is actually the 0.15.78571 version.

We use an internal ever increasing number as the third part of the version number. But at some point it overflowed on windows. ([ref](https://learn.microsoft.com/en-us/windows/win32/msi/productversion)) and we have not spent time working around that (properly) yet, so you end up with those warnings. Sorry about that. 

I'll attempt to release a version with a proper version number next week.

**Comment by Kimbsen** [comment]
Released 0.15.80533.
