### ISSUE TITLE
Feature Request: Remove archived files from jottacloud

### ISSUE THREAD

**Issue by marlind89** [jotta/jotta-cli-issues#192]
Hi,

Is it possible to remove files located on jottacloud that have been uploaded via `jotta-cli archive`?

I want to upload a backup via `jotta-cli archive` periodically, but I only want to keep the 3 most recent ones in order to save space. To accomplish this I would have to delete older backups programmatically, but I can't find any api in the cli for this. I am aware I could go to the website and remove them from there but it would be great if this could be automated.

Thanks!

**Comment by Kimbsen** [comment]
There is currently no way to do this using jotta-cli. Only the manual method you already discovered.

But we only keep the 5 most recent versions of a file, so its almost as you want it already.

**Comment by marlind89** [comment]
Ah cool, wasn't aware of that. Then I won't be needing this. Thanks!
