### ISSUE TITLE
jotta-cli archive can only archive files, not directories 

### ISSUE THREAD

**Issue by torarnv** [jotta/jotta-cli-issues#2]
```
❯ jotta-cli archive /tmp/foo
Interpretting [/tmp/foo] as [/tmp/foo]
Error: [2] read /tmp/foo: is a directory
```

Would be nice, but not critical.

**Comment by existemi** [comment]
The archive feature is meant to be used for single file upload with great
flexibility, as you have the option to place files in subdirectories based on
the `--remote` argument or generate a share link with `--share`.

If you just want to backup the directory, please consider using `jotta-cli add /tmp/foo`

Uploading all files in `/tmp/foo` with `archive`:
```
find /tmp/foo -type f | while read file; do jotta-cli archive ${file} --nogui; done
```

If you want to keep the subdirectory structure intact:
```
find /tmp/foo -type f | while read file; do jotta-cli archive ${file} --nogui --remote ${file%/*}; done
```

**Comment by torarnv** [comment]
Ah, thanks, I missed the `--remote` argument!
