### ISSUE TITLE
Feature Request: FreeBSD support

### ISSUE THREAD

**Issue by jinie** [jotta/jotta-cli-issues#20]
Seeing you have Linux and Darwin support, adding FreeBSD to the list of supported platforms should be trivial.
FreeBSD support would also allow FreeNAS users to use this utility.

**Comment by Kimbsen** [comment]
This has been added in the 0.4 release

http://docs.jottacloud.com/jottacloud-command-line-tool/installing-the-command-line-tool/jottacloud-cli-for-freebsd

**Comment by jinie** [comment]
fantastic support! 
I'll give it a spin right away.

**Comment by jinie** [comment]
the /usr/share files are missing from both amd64 and i386 packages.

I created a "freebsd'ish" startup script (attached).

* extract files into /usr/local/{bin, share}
* copy script to /usr/local/etc/rc.d and name it "jottad", set execute permissions on it.
* create /usr/local/etc/jottad
* add 'jottad_enable="YES"' to /etc/rc.conf

To run jottad execute "service jottad start" and it should be running.


[jottad.txt](https://github.com/jotta/jotta-cli-issues/files/1738084/jottad.txt)

**Comment by iko3** [comment]
Did anyone manage to get it to work on FreeNAS ? I'm constantly getting `WARNING: run_rc_command: cannot run /usr/local/bin/jottad` error

**Comment by shkm** [comment]
@jinie thanks! I couldn't get mine working until I discovered you're using a `&`. Is this necessary / reasonable? I'm hopeless with rc scripts.

@iko3 It works fine on Freenas, **provided** you place the files from Jotta in the directories that jinie specifies. That is, /usr/local/bin and /usr/local/share.

@Kimbsen can we get the `rc.conf` with `installer.sh` support for BSD derivatives in the released tar? A working out of the box experience on FreeNAS is quite a win, I think!

**Comment by jinie** [comment]
@shkm the & detaches the console, releasing control back to the calling daemon. ( I.e. http://www.linuxcommand.org/lc3_lts0100.php )

Ideally the jottad daemon should have an option to detach itself, but this essentially does the same.

I’m not running it under FreeNAS, but on a FreeBSD server I have running. I’m currently migrating it to a docker image to run directly on my Synology nas.

**Comment by Kimbsen** [comment]
@shkm We do not currently have a proper test/packaging setup for freebsd so we won't prioritize adding those files now. We do want to do it eventually though.

**Comment by gt2416** [comment]
On FreeNAS Im also getting the  WARNING: run_rc_command: cannot run /usr/local/bin/jottad error

I'm sure my files are in the right place. If you untar in root it places them properly but Im still getting the error. I used the rc script, gave it chmod x+u permissions... What am I missing ?
