### ISSUE TITLE
Server 2016 - "Error: [2] Invalid path" adding folders

### ISSUE THREAD

**Issue by masterchrister** [jotta/jotta-cli-issues#23]
Having some problems adding folders to my newly installed Jottacli.
Have tried different steps, including changing the user the jottad runs as as well as the services user for the .msi package.

Trying to add "any" folder or path to Jotta, gives me "Error: [2] Invalid path"
C:\>jotta-cli add d:
Interpretting [d:] as [D:\]
Error: [2] Invalid path

(Have also tried to add folder on C: with the same result)

Can't find anything useful in my log either regarding the error.

**OS Information**
MS Server 2016 (Core) part of a domain.

**Jotta Information**

C:\>jotta-cli version
  jotta-cli     version 0.3.4269
  jottad        version 0.3.4269
  jottad        host    TCBACK01
  jottad        path    C:\Program Files (x86)\JottaCli\jottad.exe
  jottad        appdata C:\Users\s_jottacloud/.jottad

**Comment by Soerboe** [comment]
I also get that error when trying to add a folder at the root path in linux, e.g.
`jotta-cli add '/filer' `

I got an answer from JottaCloud saying that this functionality will be present in a future release.

**Comment by masterchrister** [comment]
Thanks @Soerboe 

From what i can see, i'm not even able to add any subfolders or other folders from other drives or shares.

**Comment by Soerboe** [comment]
I guess it is related to https://github.com/jotta/jotta-cli-issues/issues/11

**Comment by Kimbsen** [comment]
This should be resolved with the 0.4 release if D: is not a network share. There are still issues to be resolved regarding network shares on windows for jotta-cli. But we intend to support those eventually as well.

**Comment by masterchrister** [comment]
Thanks @Kimbsen 
Issue has been resolved and works on both Server 2016 and Server 2016 with GUI.
