### ISSUE TITLE
Unsupported Exfat in UBUNTU

### ISSUE THREAD

**Issue by Exellent1988** [jotta/jotta-cli-issues#25]
I have an USB Drive which is in exfat formatted, so i cant back it up neither to archive nor via add
 I'm getting the following Error:

`Error: [2] Could not add path to backup: Unsupported filesystem [FUSE_SUPER_MAGIC] for key [0x65735546]`
or
` Error: [2] Unsupported filesystem [FUSE_SUPER_MAGIC] for key [0x65735546]`

Any Ideas?!

**Comment by Kimbsen** [comment]
This should be resolved now with the 0.4 release.
