### ISSUE TITLE
ElementaryOS LUKS encryption, unsupported file system ECRYPTFS_SUPER_MAGIC

### ISSUE THREAD

**Issue by mat-czernek** [jotta/jotta-cli-issues#26]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):*0.3.4269*

**Description of problem:*Error message when adding new path to the backup repository:

Command: **jotta-cli add /home/herk/Backup-CLI-Test/**

Result: **Error: [2] Could not add path to backup: Unsupported filesystem [ECRYPTFS_SUPER_MAGIC] for key [0xf15f]**

*

**Expected:**

Path added into the backup list.

**jotta-cli status (`jotta-cli status`):**
```
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
This should be resolved now with the 0.4 release.
