### ISSUE TITLE
Ignored files without permission gives warning

### ISSUE THREAD

**Issue by Soerboe** [jotta/jotta-cli-issues#27]
**jotta-cli release (`jotta-cli version`):**

  jotta-cli     version 0.4.4914
  jottad        version 0.4.4914
  jottad        host    Sandwich
  jottad        path    /usr/bin/jottad
  jottad        appdata /var/lib/jottad

**Description of problem:**
I have the following .jottaignore file in my home folder on Linux:

    .*
    Dropbox/
    Nedlastinger/

    # include .jottaignore
    !.jottaignore

The jottad user has not access to some dotfiles and Dropbox folder both which should be ignored. However jotta-cli status reports

    Path      : /home/daghenning
    Files     : 25804 files / 262.37MiB
    Status    : 2 files (24.38KiB) could not be backed up
    ---- The following paths could not be backed up ----
    /home/daghenning/Dropbox => open /home/daghenning/Dropbox: permission denied
    /home/daghenning/.adobe => open /home/daghenning/.adobe: permission denied
    /home/daghenning/.dbus => open /home/daghenning/.dbus: permission denied
    /home/daghenning/.dropbox => open /home/daghenning/.dropbox: permission denied
    /home/daghenning/.gconf => open /home/daghenning/.gconf: permission denied
    /home/daghenning/.gnome => open /home/daghenning/.gnome: permission denied
    /home/daghenning/.gnupg => open /home/daghenning/.gnupg: permission denied

**Expected:**
I would expect that when files are ignored jotta-cli should not try to access the files.

**Comment by Kimbsen** [comment]
I would have the same expectation you did. We'll get that fixed.

**Comment by Kimbsen** [comment]
We just released 0.4.4986 which should solve this issue.

**Comment by Soerboe** [comment]
Confirmed working.
