### ISSUE TITLE
Message about new version - I'm on new version

### ISSUE THREAD

**Issue by EldarAron** [jotta/jotta-cli-issues#29]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
```
jotta-cli     version 0.4.4986
jottad        version 0.4.4914
```

**Description of problem:**
When I check status or run any jotta-cli command I get a message:
```
A new version of Jotta Cli is availiable.
Please update to version 0.4.4986
```
But I have the latest version.
**Expected:**
No message about new version since I'm on the new version

**jotta-cli status (`jotta-cli status`):**
```
---------------------------
 A new version of Jotta Cli is availiable.
 Please update to version 0.4.4986
------------------------------------------------------------------------------
 Account   : xxxxxx@aron.no
 Usage     : 2.39TiB / ( Unlimited )
 Device    : Eldaron Server
------------------------------------------------------------------------------
 ###### PAUSED UNTIL Fri Mar 2 23:41:05 (60 hours 15 min) ######
------------------------------------------------------------------------------
 Backups   :
------------------------------------------------------------------------------
   Path      : /media/Backup
   Files     : 6517 files / 255.26GiB
   Status    : Up to date!

------------------------------------------------------------------------------
   Path      : /media/Data500
   Files     : 5147 files / 5.80GiB
   Status    : Up to date!

------------------------------------------------------------------------------
   Path      : /media/Media
   Files     : 31676 files / 510.48GiB
   Status    : 38 files (13.07GiB) could not be backed up

------------------------------------------------------------------------------
   Path      : /var/www
   Files     : 25019 files / 771.13MiB
   Status    : Up to date!

------------------------------------------------------------------------------
OK
```
I know about the 38 files. I'm in the prosess to replace a disk from BTRS raid1. It's a slow process. That's why I have paused the backup. But anyway. It' dosen''t inflict on the message about a new version available. 

`apt update` gives me the following message:
`All packages are up-to-date.`

**Comment by Kimbsen** [comment]
the jotta-cli binary is updated, but jottad is still running the previous version. You probably just need to restart jottad for the update to take effect. 

But be aware that jottad will not remember it was paused after the restart. So you probably want to wait with restarting until you sorted your raid set.

**Comment by EldarAron** [comment]
Thanks! I didn't pause jottad before I started the replace process. But because it was slow I read that one should limit the access to the mount. 
So I did a `service jottad restart` and then the `jotta-cli pause 72h`. That worked.
