### ISSUE TITLE
Log file is created in /var/lib/jottad

### ISSUE THREAD

**Issue by hernil** [jotta/jotta-cli-issues#30]
**jotta-cli release (`0.4.4986`):**

**Description of problem:**
The log file is created in /var/lib/jottad/jottabackup.log on Ubuntu 16.04 which is not following any conventions. 

**Expected:**
Log file created in /var/log/jottad/ 

**Additional info:**
The standard template make me seem strict and angry so I'm throwing in a smiley :smile:

**Comment by joakimlemb** [comment]
Hopefully the default log location is moved to /var/log/.
If the default is not moved there should at least be possible for users to override the location in a config file.

**Comment by coopersimon** [comment]
This has been added to the newest version of jottad (0.10.43844). You can set a custom location via the .ini file.

You can add
```
[settings]
LogfileDir=/var/log/jottad
```

To a file called `/etc/jottad/config.ini`

More details here: https://docs.jottacloud.com/en/articles/2750154-jottacloud-cli-configuration
