### ISSUE TITLE
Where is the log file located on Ubuntu?

### ISSUE THREAD

**Issue by sirajuddin97** [jotta/jotta-cli-issues#34]
**jotta-cli release (`jotta-cli version`):** 0.4.4986

**Description of problem:** There is no problem, I just have a question. I'm running jotta-cli on Ubuntu 16.04, where is the log file located? Thanks in advance.

**Expected:** -

**jotta-cli status (`jotta-cli status`):** -

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)** -

**Traceback** -

**Additional info:** -

**Comment by existemi** [comment]
Depending on configured `datadir`, `jottabackup.log` is created inside this directory. By default this is  `/var/lib/jottad/jottabackup.log`, and you should see where the deamon created the logger with `journald`:
```
# journalctl -u jottad -e
Apr 04 12:38:10 hostname jottad[11982]: [11982] creating logger @ /var/lib/jottad/jottabackup.log
```
