### ISSUE TITLE
The file system thing...

### ISSUE THREAD

**Issue by piedrola** [jotta/jotta-cli-issues#38]
Hey guys, I'd love to backup a remote filesystem. In the FAQs Roland advices 

> you should when possible not add any directories with mounts in them, but rather add the mount itself. 

[http://docs.jottacloud.com/jottacloud-command-line-tool/jottacloud-command-line-tool-faq-s/what-file-systems-are-supported-by-jottacloud-cli](url)

Is it even possible with Linux/Ubuntu? I need a directory where I mount the filesystem. When adding this I will get the error message from the FAQ page. 

Can anyone explain further on this topic? 
Thanks a lot
Daniél

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
