### ISSUE TITLE
Negated ignores not working?

### ISSUE THREAD

**Issue by carestad** [jotta/jotta-cli-issues#39]
**jotta-cli release (`jotta-cli version`):** 0.4.4986

**Description of problem:** Ignores file with negated ignores does not seem to work / taken into account

I am trying to set the following ignore file to jotta:

```
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*

/home/user/.config/
!/home/user/.config/autostart
/home/user/VirtualBox VMs/
```

Where the whole `.config` folder is skipped, while I in fact want the `autostart` subfolder there to be backed up. Re-ordering it so it looks like below does not work either:

```
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*

!/home/user/.config/autostart
/home/user/.config/
/home/user/VirtualBox VMs/
```

Do these not work?

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
