### ISSUE TITLE
brew services start jotta-cli not optional on macOS

### ISSUE THREAD

**Issue by torarnv** [jotta/jotta-cli-issues#4]
The macOS instructions notes `brew services start jotta-cli` as optional, but without it the cli reports:

```
❯ jotta-cli login
Error: Could not connect to jottad
```

http://docs.jottacloud.com/jottacloud-command-line-tool/installing-the-command-line-tool/jottacloud-cli-for-macos

**Comment by rolandrabben** [comment]
Fixed in docs now.
