### ISSUE TITLE
Implement additional http headers for webhooks

### ISSUE THREAD

**Issue by endor-force** [jotta/jotta-cli-issues#43]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
  jotta-cli     version 0.4.4986
  jottad        version 0.4.4986

**Description of problem:**
When adding webhooks to discord it returns an error stating that receiving server is missing expected definition of Content-Type in the http header.

Discord, using webhooks, documentation: 
https://support.discordapp.com/hc/sv/articles/228383668

**Expected:**
Possibility to send webhooks to discord.

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**

Data sent in webhook, example welcome confirmation captured with netcat:
```
POST / HTTP/1.1
Host: 192.168.1.132:1234
User-Agent: Go-http-client/1.1
Content-Length: 104
Accept-Encoding: gzip

{"username":"Jottacloud Command-line Tool","text":"Hello from jottad on the_moon!\nYour webhook is working!"}
```

Error in log
```
pid:2793 2018/05/17 20:32:04 Invalid status code for webhook[400] {"_misc": ["Expected \"Content-Type\" header to be one of set(['application/json', 'multipart/form-data', 'application/x-www-form-urlencoded'])."]}
```

**Traceback**
```

```

**Additional info:**
Yay, keep it up 😄

**Comment by Kimbsen** [comment]
this was added in version 0.5.13645
