### ISSUE TITLE
jottad did not start in raspberry pi 

### ISSUE THREAD

**Issue by metrolan** [jotta/jotta-cli-issues#44]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
Error: Could not connect to jottad

**Description of problem:**
Hi there!

I have jottacloud installed in somes systems: desktop, portable, raspberry-pi... This last suddenly gives the error that can't connect to jottad.

Having a look at jottabackup.log I can read:

_jauth error ciphertext too short_

So I thin that was a login errror.

I've purged the installation and resinstalled jotta-cli, but I still can't connect to jottad, and this time even I have no jottabackup.log, so there are the last lines with journalctl -u jottad.service -b:

> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Service hold-off time over, scheduling restart.
> may 24 21:06:38 nextcloudplus systemd[1]: Stopped Jottacloud cli.
> may 24 21:06:38 nextcloudplus systemd[1]: Started Jottacloud cli.
> may 24 21:06:38 nextcloudplus jottad[6481]: pid:6481 2018/05/24 21:06:38 Checking custom datadir /etc/jottad/config.ini
> may 24 21:06:38 nextcloudplus jottad[6481]: [6481] creating logger @ /var/lib/jottad/jottabackup.log
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Main process exited, code=exited, status=1/FAILURE
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Unit entered failed state.
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Failed with result 'exit-code'.
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Service hold-off time over, scheduling restart.
> may 24 21:06:38 nextcloudplus systemd[1]: Stopped Jottacloud cli.
> may 24 21:06:38 nextcloudplus systemd[1]: Started Jottacloud cli.
> may 24 21:06:38 nextcloudplus jottad[6488]: pid:6488 2018/05/24 21:06:38 Checking custom datadir /etc/jottad/config.ini
> may 24 21:06:38 nextcloudplus jottad[6488]: [6488] creating logger @ /var/lib/jottad/jottabackup.log
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Main process exited, code=exited, status=1/FAILURE
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Unit entered failed state.
> may 24 21:06:38 nextcloudplus systemd[1]: jottad.service: Failed with result 'exit-code'.
> may 24 21:06:39 nextcloudplus systemd[1]: jottad.service: Service hold-off time over, scheduling restart.
> may 24 21:06:39 nextcloudplus systemd[1]: Stopped Jottacloud cli.
> may 24 21:06:39 nextcloudplus systemd[1]: jottad.service: Start request repeated too quickly.
> may 24 21:06:39 nextcloudplus systemd[1]: Failed to start Jottacloud cli.
> may 24 21:06:39 nextcloudplus systemd[1]: jottad.service: Unit entered failed state.
> may 24 21:06:39 nextcloudplus systemd[1]: jottad.service: Failed with result 'exit-code'.

Could you help me?

**Expected:**

**jotta-cli status (`jotta-cli status`):**
could not connect to jottad
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by djtm** [comment]
Please post relevant logs from  /var/lib/jottad/jottabackup.log

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
