### ISSUE TITLE
Archived file gets backslash as a prefix of its filename

### ISSUE THREAD

**Issue by albertony** [jotta/jotta-cli-issues#45]
Version of jottad/jotta-cli: 0.4.4986

I am uploading a file using the following command:

`jotta-cli.exe archive D:\Backup\subfolder\filename.7z --remote Backup`

The file is uploaded to the Backup folder in my Archive as expected, but looking in the Web UI the file has name "\filename.7z" - with an extra backslash prefix. When I enter the file rename function (in Web UI) it presents the current name as `\\filename.7z` (extra backslash for escaping?). Deleting both backslashes, renaming the file, works from Web UI.

**Comment by DmitriyK-CPKIO** [comment]
I confirm this behaviour even with `jotta-cli.exe archive filename.7z`

**Comment by Kimbsen** [comment]
This should be fixed in version 0.5 which we released yesterday.
