### ISSUE TITLE
Restore with jotta-cli?

### ISSUE THREAD

**Issue by rkarlsba** [jotta/jotta-cli-issues#46]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
Any
**Description of problem:**
No restore command
**Expected:**
Restore works

**jotta-cli status (`jotta-cli status`):**
```
Not relevant
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
Not relevant
```

**Traceback**
```
Not relevant
```

**Additional info:**

There has been talk about adding restore to the jotta-cli, which is critical, for some time, months, actually. Can this really be so hard to figure out?

**Comment by gt2416** [comment]
Hi, so is this possible now ?  What are the commands, the docs dont have any info on this yet.
I Just switched to jottacloud, running on FreeBSD and cli is my only option. 
When restoring there should also be an option to restore with original file permissions as thats very important to restoring linux file systems.

**Comment by rkarlsba** [comment]
No, it's not. Jotta prioritises Linux and BSD so low even a fruit fly has the brains to know they really don't care.

**Comment by Kimbsen** [comment]
We have now released version 0.5 which supports restore via the download command. 

https://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/downloading-using-jottacloud-cli
