### ISSUE TITLE
404 in sync when file exists

### ISSUE THREAD

**Issue by djtm** [jotta/jotta-cli-issues#48]
Make sure you are running the latest version of jotta-cli before reporting an issue.

Hi, I think I have found a bug in jotta-cli. 

**jotta-cli release (`jotta-cli version`):**
0.4.4986

**Description of problem:**

If the file is already present, it causes a 404 error.

That happens for apparently every file already online. status

**Expected:**

success

**jotta-cli status (`jotta-cli status`):**
```
Path : .../RAWs
Files : 3066 files / 80.28GiB
Status : 3066 files (80.28GiB) could not be backed up
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
> pid:10422 2018/07/07 09:32:08 Running scan of .../RAWs
> pid:10422 2018/07/07 09:32:08 Error uploading 
> ```json 
> {
> "Name": "x.sh",
> "Path": ".../RAWs/x.sh",
> "Size": 395,
> "Modified": "2018-06-09T17:48:42.549072988Z",
> "Created": "2018-06-10T08:55:12.196051496Z",
> "Checksum": "",
> "State": "Added"
> }
> ``` 
> => Invalid statuscode 404
> pid:10422 2018/07/07 09:32:10 Deferring scan of .../RAWs while waiting for previous queue to finish

**Additional info:**
extra systemd section:
```
[Service]
CPUShares=100
MemoryLimit=150M
BlockIOWeight=50
Nice=19
IOSchedulingClass=idle
CPUSchedulingPolicy=idle
```

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
