### ISSUE TITLE
[REQ] More control over archive destination

### ISSUE THREAD

**Issue by Fjodor42** [jotta/jotta-cli-issues#5]
According to http://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/archiving-files-with-jottacloud-cli

> Note: Files are stored in a subfolder of the Archive with the same name as the device name.

Having previously used https://github.com/Fjodor42/jottalib-ng (thank you for providing something yourselves - the speed especially seems to indicate multithreading that I never got around to and, hence, looks vastly superior), I have some directory structure in Archive, that I would very much like to keep, and, hence, I would very much like to be able to specify more directly, where the files should go.

Looking at http://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/login-and-basic-use , there is a slight chance that `--remote` facilitates this, but from the description ("_Where you want it?_"), it's a bit hard to tell...

**Comment by askeland** [comment]
The following command:
`jotta-cli archive test.txt --remote subfolder/test`

Will locate the file at "Archive/<Your device>/subfolder/test/test.txt"

**Comment by Fjodor42** [comment]
Thank you for your very swift reply, @askeland !

Indeed that was my wish, but as long as `--remote` is actually for specifying subfolders, as I had hoped for, but not verified, I can restructure the folder hierarchy from the web GUI to work with the "device" nomenclature, without it being a problem.

For completeness, I do think some option should be implemented to go outside the "device" base, but I can work with what you told me - thank you :-)

**Comment by Kimbsen** [comment]
We have removed the [device name] of the path created when using the --remote option in version 0.3.4243 that was just released.

```
jotta-cli archive file.test --remote /folder/subfolder 
```
should then upload file.test to Archive/folder/subfolder/file.test

while 
```
jotta-cli archive file.test 
```
will still upload to Archive/devicename/file.test
