### ISSUE TITLE
No access to folder

### ISSUE THREAD

**Issue by Nichlas** [jotta/jotta-cli-issues#51]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jotta-cli     version 0.4.4986
  
jottad        version 0.4.4986
jottad        host    nichlas-desktop
jottad        path    /usr/bin/jottad
jottad        appdata /var/lib/jottad

**Description of problem:**

```
------------------------------------------------------------------------------
   Path      : /mnt/Amorella/Fotoarkiv
   Files     : 0 files / 0bytes
   Status    : Up to date!
   ---- The following paths could not be backed up ----
   /mnt/Amorella/Fotoarkiv => open /mnt/Amorella/Fotoarkiv: permission denied

------------------------------------------------------------------------------

```

**Expected:**
Expected Jotta to have access to the folder.

**jotta-cli status (`jotta-cli status`):**
```
------------------------------------------------------------------------------
 Account   : <user>
 Usage     : 7.43TiB / ( Unlimited )
 Device    : DESKTOP
 Backups   :
------------------------------------------------------------------------------
   Path      : /mnt/Amorella/Fotoarkiv
   Files     : 0 files / 0bytes
   Status    : Up to date!
   ---- The following paths could not be backed up ----
   /mnt/Amorella/Fotoarkiv => open /mnt/Amorella/Fotoarkiv: permission denied

------------------------------------------------------------------------------
OK

```

**Comment by eriklysoe** [comment]
Same problem, can not backup files outside home directory
jotta-cli release (jotta-cli version):
jotta-cli version 0.4.4986

sudo jotta-cli add /media/erik/data/Data
Error: [7] stat /media/erik/data/Data: permission denied 

sudo jotta-cli add /home/erik/Data
 Added /home/erik/Data
OK

**Comment by durian** [comment]
Similar problem here, Arch Linux
```
jotta-cli version
---------------------------
  jotta-cli     version 0.4.4986
  
  jottad        version 0.4.4986
  jottad        host    margretetorp
  jottad        path    /usr/bin/jottad
  jottad        appdata /var/lib/jottad
---------------------------
```
I get "Error: [7] stat [...] permission denied" on my folders. I tried changing permissions, adding myself to jottad group and vice versa, but to no avail. Also tried running as user and as root.

**Comment by yunnanpl** [comment]
Similar, but I have stat permission denied on files and folders... (both as user and root).
The trick is that the problem occurs only on NTFS drive mounted with fuse. On linux ext4 partition everything seems fine (as user or root).
(No other tests done, as I have no other partition types)

It is important to mention that the **stat** (when run separately on files or dirs) function works well everywhere, on every file and as every user.

`jottad executable : /usr/bin/jottad
jottad appdata    : /var/lib/jottad
jottad version    : 0.5.14050
jotta-cli version : 0.5.14050`

`Linux comp 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux`

**Comment by widert** [comment]
Same problem here

>    Path      : /home/wide/macDocs
   Files     : 0 files / 0bytes
   Status    : Up to date!
   ---- The following paths could not be backed up ----
   /home/wide/macDocs => lstat /home/wide/macDocs/.AppleDouble: permission denied

**Comment by Kimbsen** [comment]
We have added an article about setting permissions on linux so that jottad gets the required access and can backup folders: https://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/jottacloud-cli-and-permissions-on-linux.

If you have any comments/feedback regarding the post please post them to a new issue.
