### ISSUE TITLE
Files without extention gets ignored

### ISSUE THREAD

**Issue by fiskeren** [jotta/jotta-cli-issues#52]
**Running version:** jotta-cli version 0.4.4986

I use Ubuntu as my desktop distro, and I am a happy jottacloud customer, but I have found that jotta-cli does not sync files without extensions.
Unfortunately I take a lot of notes using vim, and often I don't put any extension on the file, so my notes does not backup the files.
Can this please be fixed?   

**Expected:** Back up all files including them without file extension.

**jotta-cli status (`jotta-cli status`):** Status    : Up to date!

**Comment by AStrunk** [comment]
Please close. Figured it out. ;-)

**Comment by gt2416** [comment]
Could you post your solution please ?

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
