### ISSUE TITLE
Feature request: Additional parameters to archive command

### ISSUE THREAD

**Issue by KevinMidboe** [jotta/jotta-cli-issues#53]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**  0.4.4986

**Type of issue:** Feature request

**Feature description:**  
More parameter options to archive command to increase functionality. Would be nice to be able to list contents of the users archive directory. Alongside listing archives being able to remove files in your archive would be beneficial to enable freeing up space by cleaning up the archive. 

**Additional features to jotta-cli:**  
Feature request addresses adding additional optional parameters to the jotta-cli archive command.
`jotta-cli archive --list`: list the contents of the archive.
`jotta-cli archive --remove [path/to/archive-file]`: remove a item from the archive.

**Comment by Kimbsen** [comment]
If you are on linux or osx you can "browse" the archive using the ls or download commands with  [bash completion](https://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/bash-completion-macos-and-linux). 

```jotta-cli download Archive/ [TABTAB]```

I don't think we will be adding --remove. You can do this today on jottacloud.com.

**Comment by KevinMidboe** [comment]
Ok, thanks for the reply. 
My use case would be to remove old backups programatically from a headless linux server so this I wouldn't need to be a manual task I needed to repeat every week. 

But thanks for the reply, great to know about the list option. 
Keep up the good work 👍
