### ISSUE TITLE
Please add the ability to schedule backups

### ISSUE THREAD

**Issue by phunni** [jotta/jotta-cli-issues#54]
Make sure you are running the latest version of jotta-cli before reporting an issue.

Version: 0.4.4986

It would be really useful to be able to schedule backups - including setting a time period during which backups are allowed to run and aren't allowed to run outside of that(those?) times.

**Comment by mabahj** [comment]
You could sort of work around this by creating a cron that for example runs "jotta-cli pause 12h" every morning, if you want it to only run at night. I think that should give you a quiet period, although it is not the proper scheduling feature you're asking for.

**Comment by Kimbsen** [comment]
For now we encourage looking at this in the opposite direction. As the previous poster commented using ```jotta-cli pause``` as documented here: https://docs.jottacloud.com/en/articles/254735-how-to-pause-jottacloud-cli

**Comment by coopersimon** [comment]
You can set the scan interval with `jotta-cli config set scaninterval [duration]` and pause with `jotta-cli pause [duration]`
