### ISSUE TITLE
"jotta-cli rem" crashes

### ISSUE THREAD

**Issue by cpkio** [jotta/jotta-cli-issues#55]
**jotta-cli release:**
`version 0.4.4986` for Windows

**Description of problem:**
`jotta-cli` for windows crashes with out of range error when running with `jotta-cli rem` — err != nil exception not caught I suppose :)

**Expected:**

Expected not seeing this:
```panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
        /go/src/git.jotta.us/dev/jotta-nix-backup/jotta-cli/main.go:377 +0x2f99```

**Comment by Kimbsen** [comment]
This should be fixed in version 0.5 which we released yesterday.
