### ISSUE TITLE
Error: [2] Invalid statuscode 460 when out of quota

### ISSUE THREAD

**Issue by magnuhho** [jotta/jotta-cli-issues#57]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.4.4986 / windows

**Description of problem:**

When you run out of quota, jotta-cli returns "Error: [2] Invalid statuscode 460"

**Expected:**
Error: [2] Out of quota" - or something similar

```
**jotta-cli status (`jotta-cli status`):**

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
none
```

**Traceback**
```
none
```

**Additional info:**

none

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)

**Comment by magnush0lm** [comment]
Well. The problem does not go away just because you close the issue

**Comment by coopersimon** [comment]
The issue was fixed a while ago. You get a more verbose message if you call `jotta-cli status` with a full account. If you are experiencing an issue with this on the latest release, please open a new issue.

**Comment by magnush0lm** [comment]
New issue created, #122.
