### ISSUE TITLE
Backup restarts when specified pause-time expires...

### ISSUE THREAD

**Issue by pamunthe** [jotta/jotta-cli-issues#58]
jotta-cli release (`jotta-cli version`): version 0.4.4986

**Description of problem:**

The backup seems to start over whenever the timeframe specified with jotta-cli pause expires.  This makes it hard to get the backup to complete.  Is this a known issue or by design ?

**Comment by pamunthe** [comment]
Some more data showing the issues I'm having.  Snippet from /var/lib/jottad/jottabackup.log :

pid:2145 2018/12/05 14:00:10 Pausing for 9h0m0s. Resume @ 2018-12-05 23:00:10.786939685 +0100 CET m=+98634.558875106
pid:2145 2018/12/05 14:00:10 Stopping scheduled backup of /nasmedia/movies
pid:2145 2018/12/05 14:00:10 Scheduler stopped
pid:2145 2018/12/05 14:00:15 Queue clearing 0 items left
pid:2145 2018/12/05 14:59:19 paused: resuming in ~8h0m51.242497785s
pid:2145 2018/12/05 15:59:19 paused: resuming in ~7h0m51.242549093s
pid:2145 2018/12/05 16:59:19 paused: resuming in ~6h0m51.242280781s
pid:2145 2018/12/05 17:59:19 paused: resuming in ~5h0m51.24245362s
pid:2145 2018/12/05 18:59:19 paused: resuming in ~4h0m51.242493827s
pid:2145 2018/12/05 19:59:19 paused: resuming in ~3h0m51.242460058s
pid:2145 2018/12/05 20:59:19 paused: resuming in ~2h0m51.240329065s
pid:2145 2018/12/05 21:59:19 paused: resuming in ~1h0m51.242440442s
pid:2145 2018/12/05 22:50:19 paused: resuming in ~9m51.242466742s
pid:2145 2018/12/05 22:51:19 paused: resuming in ~8m51.242495252s
pid:2145 2018/12/05 22:52:19 paused: resuming in ~7m51.241745138s
pid:2145 2018/12/05 22:53:19 paused: resuming in ~6m51.241717138s
pid:2145 2018/12/05 22:54:19 paused: resuming in ~5m51.242428169s
pid:2145 2018/12/05 22:55:19 paused: resuming in ~4m51.24240582s
pid:2145 2018/12/05 22:56:19 paused: resuming in ~3m51.242511356s
pid:2145 2018/12/05 22:57:19 paused: resuming in ~2m51.242440077s
pid:2145 2018/12/05 22:58:19 paused: resuming in ~1m51.24250289s
pid:2145 2018/12/05 22:59:19 paused: resuming in ~51.242093173s
pid:2145 2018/12/05 23:00:19 Resuming
pid:2145 2018/12/05 23:00:19 Running scan of /nasmedia/movies
pid:2145 2018/12/05 23:00:19 Scan completed of [/nasmedia/movies] completed in 12h31m32.405226705s [0 files 0bytes]
pid:2145 2018/12/05 23:00:21 Scan of /nasmedia/movies completed in 1.641399627s. 123 files 4.30TiB
pid:2145 2018/12/05 23:02:29 Running scan of /nasmedia/movies
pid:2145 2018/12/05 23:02:30 Scan of /nasmedia/movies completed in 455.361798ms. 123 files 4.30TiB
pid:2145 2018/12/05 23:04:39 Deferring scan of /nasmedia/movies while waiting for previous queue to finish
pid:2145 2018/12/05 23:06:19 Updating account info

Result of running jotta-cli status prior to the pause :
Tue Dec 4 14:00:00 CET 2018   Status    : Transferring 54 files / 1.93TiB remaining

Result of running jotta-cli status after the pause :

Wed Dec 5 23:10:10 CET 2018   Status    : Transferring 71 files / 2.55TiB remaining

No new files has been added so what is the reason for the jump in files remaining ?

**Comment by b01t** [comment]
I've also seen this. It seems jotta-cli throws away the queue file when it pauses, and doesn't update the db file with what's already uploaded, so if you're trying to back up a large amount of files, and can't get through indexing all of them before the next pause, you'll never finish. You have to let it run until it gets through the new files, which kind of defeats the purpose of the pause.

It's not reuploading them, though. Just re-calculating the hash and running "allocate" against the server. Little bandwidth is consumed during this process.

**Comment by Kimbsen** [comment]
I've found the root cause of the issue and i'm looking for a solution. As pointed out it will not actually reupload files, just checksum them and make sure the server already has the file.

**Comment by coopersimon** [comment]
Closing this as it is stale. If this is still a problem, please open a new issue :)
