### ISSUE TITLE
Custom datadir

### ISSUE THREAD

**Issue by albertony** [jotta/jotta-cli-issues#6]
Is it possible to customize the location of the datadir? If not, can you make a command line argument or something for it?
I'm trying out the Windows version, and would like to use something different than "%USERPROFILE%\\.jottad", for instance a local folder in a portable setup (and then a .zip distribution would also be nice, although extracting the binaries from the .msi is no problem).

**Comment by Kimbsen** [comment]
This is a good idea. We'll add it in the next update.

Details to follow!

**Comment by Kimbsen** [comment]
You can set datadir using a ini configuration file.

Put the file in the following place
``` 
Windows: C:\Program Files (x86)\JottaCli\config.ini
Osx: ~/.config/jottad.ini
Linux: /etc/jottad/config.ini
```

The contents of the file could be as follows. 
```
[settings]
Datadir=C:\Users\kim\datadir
``` 

Just pushed version 0.3.4243 where this is implemented

**Comment by albertony** [comment]
Great, that was fast, and I see that you published it as a zip file as well, thanks!

I tested version 0.3.4246, and have some comments:
- The ZIP file contains files `jottad` and `jotta-cli` without the .exe extension, and they are not digitally signed (and the size and content differ slightly from those in the MSI, but that might be the missing signature).
- Custom datadir in config.ini seem to work, also specifying a relative path works. But the logfile is still written to `%USERPROFILE%\\.jottad`. I guess a workaround is to use command line option `stdoutlog`, and possibly pipe to my own log file, but ideally I would like the logfile also to be put in the custom datadir.

**Comment by Kimbsen** [comment]
Right, we'll take a look at the .zip generation. it was supposed to be the very same signed binaries. 

About the logfile, i noticed that just after i pushed 4243 . There is a later one (4246) available that logs to the correct location.

**Comment by albertony** [comment]
I was testing the 4246 build.

**Comment by Kimbsen** [comment]
I might not actually have pushed that fix then. I'll get it done tomorrow morning.

**Comment by albertony** [comment]
That's fine.
I also just noticed you did add the possibility to specify the custom datadir using command line option (`datadir PATH`) as an alternative to the config.ini file you mentioned, and I like that even better! One difference from the ini file approach, though, is that with the command line option the path must exist or else jottad exits with failure `Custom application data directory stat error: CreateFile <PATH>: The system cannot find the file specified.`. Just mentioning it, I'm not claming it is an error, maybe it is even the wanted behaviour?

**Comment by Kimbsen** [comment]
A version where jottabackup.log is created in the custom datadir is out now.

**Comment by albertony** [comment]
ZIP file is now OK (.exe extensions, signature, identical to files in MSI).
Custom datadir using command line option is also tested OK.
Thanks! :thumbsup:
