### ISSUE TITLE
Jotta: Are these issues even being read?

### ISSUE THREAD

**Issue by Hermonella** [jotta/jotta-cli-issues#60]

**Comment by Kimbsen** [comment]
Yes they are being read. They get reported to our internal tracking which we use to prioritize tasks.

I'm sorry for not responding in a long time, but we have not been able to dedicate any time to jotta-cli for a while. 

We do have an update planned for januaryish though and we are considering all reported issues when we consider what to include.

Some stuff that is more or less complete and almost definetely will be included in the next update is:

* downloading/restore of files or folders
* rate limiting of uploads and downloads
* bash completion

**Comment by shamekas** [comment]
This is a lie. This does not even begin to address the range of problems that are reported here. I'm sick of your excuses and I'm using jotta only because it's dirt cheap because your service is crap. You do what you want and have the gall to repeat over and over that you "prioritize". To hell with you all. This is a shitfest where you laugh in our face and I'm not participating in it anymore.

**Comment by DIYglenn** [comment]
> This is a lie. This does not even begin to address the range of problems that are reported here. I'm sick of your excuses and I'm using jotta only because it's dirt cheap because your service is crap. You do what you want and have the gall to repeat over and over that you "prioritize". To hell with you all. This is a shitfest where you laugh in our face and I'm not participating in it anymore.

This is not a very helpful comment. I'm also seeing some issues with Jotta-Cli, but as there are probably a smaller number of users using this feature, I do understand that it isn't prioritized.

The comments should be kept constructive - new features are in the works.
Hopefully some bug fixes to...

**Comment by shamekas** [comment]
@Kimbsen: "We do have an update planned for januaryish"

Well it's a week til March and there has been no update.

**Comment by Kimbsen** [comment]
I agree we were probably streching the ish, but at least we got it out before march!
