### ISSUE TITLE
Bandwith throttling

### ISSUE THREAD

**Issue by johankardell** [jotta/jotta-cli-issues#65]
I max out my Internet connection while sending files to Jottacloud - that's really nice, but my NAS doesn't have the power to do anything else while uploading files. Bandwith throttling would be a really nice feature to have (like - use max 10Mbps).
RClone has this feature and of course I could just use rclone, but it would be nice to have this in jotta-cli as well.

**Comment by johankardell** [comment]
I just realized that Backup can't use rclone - so bandwith throttling in jotta-cli would definitely be nice.

**Comment by who8mypnuts** [comment]
It's been requested for well over a year now...hopefully, we'll see something soon.

**Comment by Kimbsen** [comment]
We just released version 0.5 which has up/download ratelimiting.

Try: ```jotta-cli config set uploadrate 5m ``` to set it to max 5MB/s

**Comment by who8mypnuts** [comment]
Thank you so much! It's the first time in many months that I can actually use Jotta and it doesn't tear up my hard drive and that I can actually use the internet or make a phone call while it's still backing up my system.
