### ISSUE TITLE
jottad hogging CPU

### ISSUE THREAD

**Issue by Skeletorjus** [jotta/jotta-cli-issues#66]
Version 0.4.4986, Debian Stretch

jottad is wreaking absolute havoc on the CPU, constantly grabbing whatever resources it can and leaving little (if anything) for other processes.
There has to be a way to throttle CPU usage as this issue makes jotta-cli and, by extension, Jotta as a whole, unusable.

**Comment by Kimbsen** [comment]
We just released version 0.5

It should in general be less cpu intense, but there is also a throttle of sorts:
```jotta-cli config set slowmomode value```
Where value is a number 0-50 where 0 is fast and 50 is slow(less cpu/disk).
The default is 0.
