### ISSUE TITLE
ERROR  Cannot add /path/ to backup: Warning: Mountable filesystem

### ISSUE THREAD

**Issue by CHRONiCiTY** [jotta/jotta-cli-issues#68]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.5.13645
**Description of problem:**
Can't add folder
**Expected:**
Add folder

**jotta-cli status (`jotta-cli status`):**

No folders added to backup yet
OK

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
stat of /mnt/HDD/Storage/Webserver failed: Warning: Mountable filesystem

**Traceback**
```

```

**Additional info:**
Trying to add folders from a FreeBSD iocage jail (FreeNAS actually) but getting the error message in the issue title.
The folder is mounted to the jail from the host via fstab.
It's not possible to install/use jotta directly from FreeNAS since FreeNAS itself is on a read-only file system. The storage however is on a zpool which the jails have full access to.

**Comment by CHRONiCiTY** [comment]
Actually mounted the filesystem on FreeNAS as writable and then added the jc binaries and set everything up. Got the exact same error message when trying to add the folder though.
Seems odd to make a command line tool for FreeBSD and not support ZFS-filesystems.

**Comment by Kimbsen** [comment]
This is clearly a bug. What you attempted should have worked and we'll sort it out for the next release. Hopefully sometime this week or next.

**Comment by Kimbsen** [comment]
We released it today.
