### ISSUE TITLE
Feature request: ls -w

### ISSUE THREAD

**Issue by magnuhho** [jotta/jotta-cli-issues#69]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.5.14050

**Description of problem:**

jotta-cli ls -l gives a truncated version of long file names

I propose a -w(ide) switch

**Expected:**

jotta-cli ls -lw will return the full file name of the files listed

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by roflmao** [comment]
Do you have a sample output?

**Comment by magnuhho** [comment]
C:\>"c:\Program Files (x86)\JottaCli\cli\jotta-cli.exe" ls Archive/OSPrep/x86 -l
Name                                     Size  Checksum  LastModified
---------------------------------------  ----  --------  ------------
TortoiseSVN-1.9.7....in32-svn-1.9.7.msi


Expected:
TortoiseSVN-1.9.7.27907-win32-svn-1.9.7.msi

**Comment by Kimbsen** [comment]
We are still figuring out how we want ls to function. It was added pretty much only so users on windows would be able to generate paths for jotta-cli download( no bash-completion ). Truncating the filename was probably not the best idea with that in mind.

Without -l it should display the full name. But we should to do that with -l as well. Expect it in the next release.
