### ISSUE TITLE
ls does not populate Size, Checksum and LastModified

### ISSUE THREAD

**Issue by magnuhho** [jotta/jotta-cli-issues#70]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.5.14050

**Description of problem:**
jotta-cli -l shows column headers for Size, Checksum and LastModified, but the columns are empty/not populated

jotta-cli ls -l /archive/folder
Name                                     Size  Checksum  LastModified
---------------------------------------  ----  --------  ------------
file.ext

**Expected:**
Name                                     Size  Checksum  LastModified
---------------------------------------  ----  --------  ------------
file.ext                                           10 0AD7EC1DBDAECA89C1ABE9C12C36C1CAA92B321F 20.01.2014 09:32:58

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
I'm not able to reproduce this. 

Are you sure file.ext is a file and not a folder? 
Folders only have their name set, while files should have the other attributes set as well.

If it is a file i would like to take a look at the specifics of that file. Could you please open a ticket with support@jottacloud.com?

**Comment by magnuhho** [comment]
It is a file (well - all files).
I've sent an email to support@

**Comment by magnuhho** [comment]
Just noticed that Size and Last Changed is listed as "--" for these files when browsed to in the web gui at jottacloud.com
