### ISSUE TITLE
jotta-cli download does not time stamp files

### ISSUE THREAD

**Issue by magnuhho** [jotta/jotta-cli-issues#72]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.5.14050

**Description of problem:**
When downloading files with jotta-cli download files are not being correctly time stamped.
The downloaded files are time stamped with the date/time they were downloaded.

**Expected:**
CreationTime and LastWriteTime should equal Modified in the web gui.

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
This has been fixed in 0.5.14545
