### ISSUE TITLE
Error: unknown flag: --downloadid

### ISSUE THREAD

**Issue by magnuhho** [jotta/jotta-cli-issues#73]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.5.14050

**Description of problem:**
jotta-cli list downloadinfo requires a --downloadid flag to identify which download to list info for

https://docs.jottacloud.com/jottacloud-command-line-tool/installing-the-command-line-tool/release-notes-for-jottacloud-cli

When calling jotta-cli list downloadinfo you get an error saying --downloadid is an unknown flag

C:\>"c:\Program Files (x86)\JottaCli\cli\jotta-cli.exe" list downloads
e5a8f0860d /archive...4224.exe => C:\Borts...4224.exe: 1 (392.77KiB) remaining of 1 (392.77KiB)
OK

C:\>"c:\Program Files (x86)\JottaCli\cli\jotta-cli.exe" list downloadinfo
Error: you need to specify a --downloadid

Usage:
  jotta-cli list downloadinfo [flags]

Flags:
  -h, --help   help for downloadinfo
      --json   output data as json

Global Flags:
      --host string   the ip address of the host jottad is running on (default "127.0.0.1")
      --port string   the port jottad is listening on (default "14443")

OK

C:\>"c:\Program Files (x86)\JottaCli\cli\jotta-cli.exe" list downloadinfo --downloadid=e5a8f0860d
Error: unknown flag: --downloadid
Usage:
  jotta-cli list downloadinfo [flags]

Flags:
  -h, --help   help for downloadinfo
      --json   output data as json

Global Flags:
      --host string   the ip address of the host jottad is running on (default "127.0.0.1")
      --port string   the port jottad is listening on (default "14443")
**Expected:**

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```


```

**Traceback**
```

```

**Additional info:**

--downloadid is not listed under Flags: in the usage section of jotta-cli list downloadinfo

**Comment by magnuhho** [comment]
Another interesting observation:
"jotta-cli list downloads" and "jotta-cli download --watch" seem to disagree on whether there are ongoing downloads...

C:\Program Files (x86)\JottaCli\cli>jotta-cli.exe list downloads
e5a8f0860d /archive...4224.exe => C:\Borts...4224.exe: 1 (392.77KiB) remaining of 1 (392.77KiB)
OK

C:\Program Files (x86)\JottaCli\cli>jotta-cli.exe download --watch

No current downloads

C:\Program Files (x86)\JottaCli\cli>jotta-cli.exe list downloads
e5a8f0860d /archive...4224.exe => C:\Borts...4224.exe: 1 (392.77KiB) remaining of 1 (392.77KiB)
OK

**Comment by Kimbsen** [comment]
Just released version 0.5.14545 which fixes this.

It also renamed the `list downloadinfo` command to `list downloaderrors` which is more correct
