### ISSUE TITLE
Please add support for piping to STDIN

### ISSUE THREAD

**Issue by albech** [jotta/jotta-cli-issues#74]
Having the ability to piping to STDIN would allow for on-the-fly file manipulation like split, encryption and compression.

Thanks in advance

**Comment by Kimbsen** [comment]
Its an interesting thought and i'll think on if/how we can add it.

**Comment by coopersimon** [comment]
We've just released version 0.7.35160 which allows piping downloads to STDIN and piping from STDOUT to upload to the archive.
