### ISSUE TITLE
ERROR stat ... permission denied

### ISSUE THREAD

**Issue by brasmus** [jotta/jotta-cli-issues#75]
Jeg kjører Ubuntu Bionic på en litt eldre 32-bit maskin, og har fått backet-opp noen filer tidligere. Backupen ble ikke ferdig, og nå får jeg en feilmelding: 'ERROR stat MyFiles: permission denied'. og med jotta-cli status får jeg 'Status : Unable to get filesystemid for path: mypath error:jottad does not have permission to stat the folder'.

**Comment by Kimbsen** [comment]
På ubuntu kjører jottad som en egen bruker: jottad. Denne brukeren trenger tilgang til mappen du prøver å legge til backup.

**Comment by brasmus** [comment]
Hei,

Det hjalp meg ikke så veldig. Har forsøkt med de ulike tipsene, men uten
suksess.

Jeg forsøkte chown -R for å sette eier av katalog til jottad, uten at det
hjalp.

Informasjonen jeg får med jotta-cli status ser ikke betryggende ut:

[image: image.png]
×

rasmus.benestad@physics.org
@RasmusBenestad
mobil: +47-41122662 <http://keys.gnupg.net>

**Comment by roflmao** [comment]
Vil anbefale å la jottad kjøre som jottad brukeren og heller melde brukeren din (evnt den du skal ta backup av som har eierskap til filene) inn i gruppen til jottad:

```
usermod -G jottad dittbrukernavn
```

**Comment by Skeletorjus** [comment]
Det siste forslaget må du absolutt ikke finne på å gjøre uten -a (append)!
Altså:
`usermod -a -G jottad dittbrukernavn` 
blir det riktige med mindre du ønsker å miste tilhørighet til alle andre grupper enn jottad.

**Comment by existemi** [comment]
@Skeletorjus Ja, du har så klart helt rett. Jeg har oppdatert kommentaren slik at det ikke er noen som vil endre opp med å kjøre `usermod` uten append.

**Comment by Kimbsen** [comment]
We have added an article about setting permissions on linux so that jottad gets the required access and can backup folders:  https://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/jottacloud-cli-and-permissions-on-linux.

If you have any comments/feedback regarding the post please post them to a new issue.

**Comment by brasmus** [comment]
Jeg forsøker og jeg forsøker, men stanger fremdeles hodet i veggen. Null sukksess. Kan dere sette opp en helhetlig oppskrift om hvordan det skal gjøres uten å henvise til ulike sider der jeg likevel ikke finner svaret (godt gjemt?). Jeg finner ingen /etc/init/jottad-fil som kan endres. Jeg har ennå ikke funnet noen tips om hvordan man lar jottad kjøre som jottad-brukeren. Slike ting er greit å få inn med teskje, selv for folk som har litt erfaring med Linux. Hvis det viser seg å være håpløst, får jeg finne en annen skyløsning. Synd, for jottad så så lovende ut.

**Comment by roflmao** [comment]
@brasmus Lei for at du føler det sånn. Bionic kjører systemd som standard og kjører som jottad by default. Så det du trenger skal være "First solution" under https://docs.jottacloud.com/jottacloud-command-line-tool/using-the-command-line-tool/jottacloud-cli-and-permissions-on-linux .

**Comment by brasmus** [comment]
Hei,

Jeg følger instruksene, men det hjelper ikke. Jeg tror jeg avlutter
abonnementet. Beklager.



rasmus.benestad@physics.org
@RasmusBenestad
mobil: +47-41122662 <http://keys.gnupg.net>
