### ISSUE TITLE
jotta-cli keeps re-checksumming all the files

### ISSUE THREAD

**Issue by b01t** [jotta/jotta-cli-issues#79]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
-------------------------------------------
jottad executable : /usr/bin/jottad
jottad appdata    : /mnt/jotta
jottad version    : 0.5.14545
jotta-cli version : 0.5.14545
-------------------------------------------

**Description of problem:**
After saying "Up to date!" for any given path, it re-checksums all the files an hour later, on the next scan. It doesn't upload them, but they're checksummed, which puts a strain on our file server.

**Expected:**
Jottad should be happy when the timestamp and size of a given file matches what's reported by "stat" on the machine jottad is running on.

**jotta-cli status (`jotta-cli status`):**
I unfortunately can't share this, as it's a business account with company data on it.
The status goes from "Up to date!" to "Scanning" to "Transferring <everything>". Then it re-checksums and runs "allocate" on everything.

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
See above. I can send you a private email if you need more.

**Additional info:**
I dug around in the "db" file and compared timestamps and sizes with the output of "stat". They match, at least for the 10 or so files I checked. Is there anything else I can check?

How does jottad figure out whether or not it needs to checksum a given file?

**Comment by Kimbsen** [comment]
It should be doing exactly what you expect. In that it checks the file size and modified timestamp on scan, and only checksums if they have changed. 

Could you send an email to support@jotta.no and we can continue the discussion there?

**Comment by b01t** [comment]
Done :)

**Comment by Kimbsen** [comment]
Just released 0.5.15025 which should fix the problem causing the redundant checksumming of files.

**Comment by b01t** [comment]
I can confirm this fixed the issue for me. Thanks :) :+1:
