### ISSUE TITLE
Error: Unable to get filesystemid for path: <> error:stat format T: exit status 1

### ISSUE THREAD

**Issue by yngvar** [jotta/jotta-cli-issues#80]
jottad version: 0.5.15025 (first observed in 0.5.14050)
hardware: Asustor AS-304T NAS
os: Linux 3.4.26 i686 (ASUSTOR Data Master (ADM) / BusyBox v1.19.3)

I have been able to run the jotta x86 linux binary (from https://repo.jotta.us/archives/linux/x86/) up until version 0.4.4986 (last run April 7 2019). 
Since installing version 0.5.14050 and newer versions, currently 0.5.15025, the backup service has been unable to scan the file system and upload changes.
I observe the following errors in the application log:

    pid:6842 2019/04/08 22:10:01 unable to get filesystemid for path: /share/Music error: stat format T: exit status 1
    pid:6842 2019/04/08 22:10:01 Loaded /share/Music => Music

This repeats for every directory I've added to the backup, and every time I try to run the service.
- Why has this started happening lately, but not in versions up until 0.4.4986? 
- Is there anything I can do to fix this? 
- If not, is there anything you can do to fix this?

Best regards, Yngvar

**Comment by Kimbsen** [comment]
We are still iterating on how to best provide a sane and safe backup experience. We are clearly not there yet.

We added this check in 0.5. The reason we added this specific check is to ensure that we don't delete the content of a backed up folder in the case where someone has added a folder to backup and that folder is mounted from a different filesystem. It seems to be somewhat common for these folders to be unmounted(or just not mounted yet) for various reasons and when that happens it appears empty to jottad and jottad deletes the remote copy of the folders contents.

If you contact support@jottacloud.com and reference this issue i can take a look at your specific case and get working on a fix.

**Comment by kenavn** [comment]
Is there any resolution to this? In my case I experience the same thing running the daemon inside a container with mounted volumes from the host os. This is perfectly safe in regards to the "unmounted" situation you described, @Kimbsen; the volumes are steadily available. There should be a flag to opt-out of this check in special use cases..

**Comment by Kimbsen** [comment]
We have a fix for this. It has just not been released yet. I will try to release it this week or early next week.

**Comment by kenavn** [comment]
That is absolutely great news. Looking forward to it :)

**Comment by Kimbsen** [comment]
Its still going to be a few more days. Some stuff regarding the new login flow just isn't ready yet. just fyi.

**Comment by Kimbsen** [comment]
We just released version 0.6 which should resolve this.
