### ISSUE TITLE
 Filesystemid has changed [fd0200000000] => [fd0300000000]. Scan will not continue

### ISSUE THREAD

**Issue by gjorans** [jotta/jotta-cli-issues#81]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):0.5.15025-1

**Description of problem: Unable to backup/scan with error message:
Status    : Filesystemid has changed [fd0200000000] => [fd0300000000]. Scan will not continue

This happened after resizing the volume that is on the mountpoint I do backup on

**Expected:**
scan and do backup

**jotta-cli status (`jotta-cli status`):

```
Filesystemid has changed [fd0200000000] => [fd0300000000]. Scan will not continue
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
pid:17006 2019/05/23 14:53:47 Error starting scan Filesystemid has changed [fd0200000000] => [fd0300000000]. Scan will not continue
```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
Thanks. That is very interesting. I was not aware that resizing a volume would change its id. 

As a short term fix you can `jotta-cli rem /path/to/folder`and then `jotta-cli add /path/to/folder`it again.

But for the long term i think an extra command something like `jotta-cli add --confirmexisting /path/to/folder` or something like that will be needed as i don't think we programatically will be able to determine if its just a resize or some other innocuous event causing the change.

I'll add it to our todo.

**Comment by gjorans** [comment]
Thanx. I will try this workaround. hopefully it will not reupload everything. it is a lot of data on a slow radio link :)

Maybe this info helps out: this LVM. I added a disk to the Volume Group and extended the Volume to cover the additional space in the VG. This was on Centos 7.

**Comment by Kimbsen** [comment]
It shouldn't reupload anything. But it will checksum all the files which can consume a lot of io/cpu for a while. 

Thanks for the additional info.

**Comment by Kimbsen** [comment]
We added `jotta-cli add --confirmexisting /path/to/folder` in version 0.6
