### ISSUE TITLE
Feature Request: access photos

### ISSUE THREAD

**Issue by Fnordbert** [jotta/jotta-cli-issues#83]
**jotta-cli release 0.5.15025**

Please add support for accessing photos from cli.
I want to be able to automate local backup of photos from connected phone apps.
Downloading huge .zip files is just ugly.
Perhaps "Photo Timeline Uploads" could be made to show up here:

> $ jotta-cli ls -l
>Name     Size  Checksum  LastModified  
>-------  ----  --------  ------------  
>Archive                                
>Backup                                 
>Sync

**Comment by Kimbsen** [comment]
I agree and i want to add Photos as a browsable/downloadable "root" similar to the three listed ones.

Its currently on a different api with some limitations that need to be overcome before i can add it though so it won't happen right now. 

But its on the todo!

**Comment by dimme** [comment]
Any progress? I would like this feature very much.

Now I have to create a copy to the "Archive" folder using the web interface, download the photos from there and then delete the folder in "Archive".

**Comment by Kimbsen** [comment]
We just released version 0.6.24236 which adds Photos as a download root.
