### ISSUE TITLE
jotta-cli exclude-photos

### ISSUE THREAD

**Issue by xerhard** [jotta/jotta-cli-issues#85]
Hi,

Is it possible to add an jotta-cli option to exclude one or more paths so the images (photos) are not shown in the Web/App Photos menu?

E.g. :   jotta-cli exclude-photos \<path\>

So result is, the excluded photos are still visible as files, but are not visible in the Jottacloud photos timeline.

---
jottad executable : /usr/bin/jottad
jottad appdata    : /var/lib/jottad
jottad version    : 0.5.15025
jotta-cli version : 0.5.15025

**Comment by Kimbsen** [comment]
No, that is not possible in jotta-cli. 

I've forwarded your suggestion to the developers in charge of photos.
