### ISSUE TITLE
Ran jotta-cli archive - but not seen on the webpage

### ISSUE THREAD

**Issue by ratnose** [jotta/jotta-cli-issues#86]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
 0.5.15025

**Description of problem:**
Completing a jotta-cli archive on a tar-ball doesn't make it appear on the webpage.
When it completed the upload restarted.

**Expected:**
After completion travail visible on webpage.

**jotta-cli status (`jotta-cli status`):**
```
jotta-cli status
------------------------------------------------------------------------------
 Account   : 5c8760349b8751013333037c
 Usage     : 50.58MiB / ( Unlimited )
 Device    : filestorage
 Backups   :
------------------------------------------------------------------------------
   Path      : /mnt/storage/commodore64
   Files     : 16 files / 2.67MiB
   Status    : Up to date!

------------------------------------------------------------------------------
   Path      : /mnt/storage/nextcloud
   Files     : 311 files / 47.91MiB
   Status    : Up to date!

------------------------------------------------------------------------------
OK
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
pid:569 2019/08/02 06:26:52 Added /mnt/storage/backup/2019-08-01.tar.gz
pid:569 2019/08/02 06:26:52 Queueing scan of added path /mnt/storage/backup/2019-08-01.tar.gz
pid:569 2019/08/02 06:26:52 Running scan of /mnt/storage/backup/2019-08-01.tar.gz
pid:569 2019/08/02 06:26:52 Sanity error for scan of path [/mnt/storage/backup/2019-08-01.tar.gz] => [readdirent: not a directory]
pid:569 2019/08/02 06:26:52 Scan completed of [/mnt/storage/backup/2019-08-01.tar.gz] completed in 2.249877ms [0 files 0bytes]

**Additional info:**
Nowhere in the log I can find that I have issued jotta-cli archive.
Even though I got an gun telling me that the tarball was uploading.

**Comment by Kimbsen** [comment]
It does look like you ran
 `jotta-cli add /mnt/storage/backup/2019-08-01.tar.gz`
and not
 `jotta-cli archive /mnt/storage/backup/2019-08-01.tar.gz`.

The `jotta-cli add` should have failed, but i just tested it locally and it seems it go through and produces the same incorrect state you see from the error messages in the logfile. 
I'll get that fixed for the next version. 

To resolve the incorrect state just run 
`jotta-cli rem /mnt/storage/backup/2019-08-01.tar.gz` 
and then to upload the tar archive:  
`jotta-cli archive /mnt/storage/backup/2019-08-01.tar.gz`

**Comment by ratnose** [comment]
I actually did both. 
Great to hear - how long sprints or release schedules you got?

**Comment by ratnose** [comment]
This is kinda embarrassing... I now know why the upload restarted.
The first think that happens is a checksum, and that I misread as an upload since it displays MiB/s.
And fo course this should not be visible on the website.
I will let run it course today and see what happens.

**Comment by ratnose** [comment]
Soon 50% in, all is going well, nothing in status, ever two hours I got this in the log:
pid:1073 2019/08/03 13:20:44 GET https://repo.jotta.us/archives/VERSION 200

200 is good so I guess that means something about archiving doing it's thing?

**Comment by Kimbsen** [comment]
The url you mentioned is just jottad checking if there is a new version of jottacli.

There should be nothing in the log regarding the archive operation unless something fails.

You should see the archive progress in the terminal you are running jotta-cli from.

**Comment by coopersimon** [comment]
Closing as I'm assuming there were no further issues (let us know if there were!)
