### ISSUE TITLE
Getsky and jotta-cli

### ISSUE THREAD

**Issue by euh2** [jotta/jotta-cli-issues#89]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jottad executable : /usr/bin/jottad
jottad appdata    : /var/lib/jottad
jottad version    : 0.5.15025
remote version    : 0.6.18332
jotta-cli version : 0.5.15025

**Description of problem:**
Before update to the new jotta-cli version and the new login-flow I wonder what happens when using other frontends (like Get, Elkjop etc)? I don't see any option to generate a token on getsky.
**Expected:**
Have a option i getsky to generate login-token.

**Comment by Kimbsen** [comment]
Right. I forgot that Get runs their own authentication system and thus we hide the settings > security tab in their version of the webapp. And that was where one would generate the token.

I'll poke the webteam and get them to enable token generation on getsky and the other frontends currently missing it.

Btw, you don't need to login after updating. jottad will update/patch its login information from the old system on its own. But you will not be able to login if you logout before we get our webapps updated.

I'll let you know when that is done.

**Comment by euh2** [comment]
Great! Thanks!


Fra: Kimbsen <notifications@github.com>
Sendt: torsdag 29. august 2019 13:21
Til: jotta/jotta-cli-issues
Kopi: euh2; Author
Emne: Re: [jotta/jotta-cli-issues] Getsky and jotta-cli (#89)

**Comment by westerp** [comment]
My backups stopped and flooded the logs with auth tokens not being ok. `jotta-cli status` just reported 0/0 as space and otherwise didn't look anything different. I hoped it would be fixed by logging out since it had something to do with tokens, but I'm unable to login with the same hostname and now all of sudden it asks for a token which I don't possess.

I'm using GetSky. When will I be able to fetch a token?

**Comment by Kimbsen** [comment]
The Token-Generation has been released for Get Sky. It should be accessible on https://www.getsky.no/web/secure when logged in.

**Comment by euh2** [comment]
Thank you!

**Comment by BjornRuud** [comment]
Token generation is gone again after Get became Telia. The page https://sky.telia.no/web/secure does not have token generation, and the other settings pages do not either.

**Comment by euh2** [comment]
@BjornRuud I think it's best to open a new issue since this issue is now closed. Even if it is the same problem🤔
