### ISSUE TITLE
jottad connected but does not respond

### ISSUE THREAD

**Issue by moshovd** [jotta/jotta-cli-issues#95]
I just realized my jotta cli havent done any backups for a long time. I'm running Jotta on a headless and updated Centos server.

 Any jotta-cli command returns: Error: Connected but jottad did not respond to query within deadline

The log shows: auth.sessiondeleted 0 pid:1902 

Jottad has been running smoothly on my machine since the cli was first introduced. I do not exactly know when it stopped working, but it must be for several weeks ago - possibly after the latest jottad update.

I'm a novice to linux and am stuck in this situation, so any help is appreciated. Thanks in advance.

**Comment by Kimbsen** [comment]
Hi. It was after the latest update yes. 

auto.sessiondeleted means an error was received from the auth server that the client could not recover from on its own. 

If you could contact support@jottacloud.com and include the logfile we can look further into what happened.

**Comment by moshovd** [comment]
Thank you, Sir, further, communication will happen via email.

**Comment by squinky86** [comment]
Were you able to get this resolved? I was told to log out and back in again, but that has not resolved the issue.

**Comment by moshovd** [comment]
Yes I did- On advice from a te tech at Jottacloud, I logged out and stopped the jottad service, emptied the contets of the directory /var/lib/jottad and then restarted jottad before logging in again. After that, jottad need to do the complete checksumming again, which will take some time. You may do a backup of the var/lib/jottad/db file before deleting it and restoring it befor starting jottad with the emptied folder if you want to avoid this waiting periode.

Hope this helps!

 

/PA

 

 

Fra: Jon Hood <notifications@github.com> 
Sendt: lørdag 9. november 2019 17.21
Til: jotta/jotta-cli-issues <jotta-cli-issues@noreply.github.com>
Kopi: moshovd <moshovd@gmail.com>; State change <state_change@noreply.github.com>
Emne: Re: [jotta/jotta-cli-issues] jottad connected but does not respond (#95)

 

Were you able to get this resolved? I was told to log out and back in again, but that has not resolved the issue.
