### ISSUE TITLE
Feature Request: Emptying the recycle bin

### ISSUE THREAD

**Issue by b01t** [jotta/jotta-cli-issues#97]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
0.6.18626

**Description of problem:**
When backing up our "backups" directory, to which the VM hosts are backed up once a week, we often get emails from you saying our storage space is almost spent. We'd like to be able to script emptying the trash can on our Jotta account, so that the old stuff gets removed automatically.

**Expected:**

**jotta-cli status (`jotta-cli status`):**
```

```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```

```

**Traceback**
```

```

**Additional info:**

**Comment by Kimbsen** [comment]
We added ```jotta-cli trash purge``` in 0.6.21799 which was released today.

**Comment by b01t** [comment]
Thank you!
