### ISSUE TITLE
Debian package fails to finish installation for sysv

### ISSUE THREAD

**Issue by shkm** [jotta/jotta-cli-issues#98]
**jotta-cli release (`jotta-cli version`):**
Latest deb (`jotta-cli version` will not run due to stopped daemon) from `https://repo.jotta.us/debian debian main`.

**Description of problem:**
Installing `jotta-cli` for a sysv system fails to complete starting the daemon due to a permissions error. Full disclosure: I'm doing this under an `ubuntu:18.04` docker image.

```
Step 8/8 : RUN apt-get install -y --no-install-recommends jotta-cli
 ---> Running in 94d03524ec20
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  jotta-cli
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 15.7 MB of archives.
After this operation, 32.7 MB of additional disk space will be used.
Get:1 https://repo.jotta.us/debian debian/main amd64 jotta-cli amd64 0.6.18626 [15.7 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 15.7 MB in 3s (6134 kB/s)
Selecting previously unselected package jotta-cli.
(Reading database ... 4680 files and directories currently installed.)
Preparing to unpack .../jotta-cli_0.6.18626_amd64.deb ...
Unpacking jotta-cli (0.6.18626) ...
Setting up jotta-cli (0.6.18626) ...
Starting jottad (sysv)...
/usr/share/jottad/install.sh: 43: /usr/share/jottad/install.sh: /etc/init.d/jottad: Permission denied
```

I've confirmed that `/etc/init.d/jottad` misses the executable bit.

**Expected:**
Daemon is started after installation

**jotta-cli status (`jotta-cli status`):**

```
Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
Nothing relevant.

**Traceback**
See above.

**Additional info:**

**Comment by existemi** [comment]
@shkm Thank you, I can confirm that we are missing the executable bit for the sysvinit script. We have a fix on the way for the install script, and it should be released later this week or early next.
